In [1]:
import pandas as pd
from chat_bots import ChatSentimento, ChatFundamentalistas, ChatAnaliseTecnica, ChatBot, ChatValuation, ChatTradutor
from coleta_dados import (DadosFundamentalistas, 
                          DadosNoticiasBuscadorYahoo, 
                          DadosNoticiasGoogle, 
                          CalculoWACC, 
                          VariacaoReceita, 
                          ValuationModoloGordon, 
                          OutrosAtivosNaoOperacionais,
                          PassivoTotalMenosDivida,
                          NecessidadeCapitalGiro,
                          IndicadoresFinanceiros,
                          ValuationFluxoCaixaDescontado)

from tratando_dados import tratando_dados_fundamentalistas, TratarDadosNoticias, TratandoDadosIndicadores, TratandoDadosValuation
from juncao_modelos_dados import ModeloValuation, ModeloFundamentos, ModeloSentimento, ModeloAnaliseTecnica
from dotenv import load_dotenv
import ipeadatapy as ip
from datetime import datetime
import pandas as pd
import yfinance as yf
import sidrapy
import warnings
warnings.filterwarnings('ignore')
load_dotenv()

USER_AGENT environment variable not set, consider setting it to identify your requests.

True

# Fundamentalista

In [2]:
tic = 'BBDC3'
data_inicio = '2020-01-01'

dados_fundamentalistas = DadosFundamentalistas(tic, data_inicio)
trat = tratando_dados_fundamentalistas(tic, data_inicio)

In [3]:
from typing import List, Any
def retransfromando_pandas(trat: List[Any]) -> pd.DataFrame:
    df = pd.DataFrame([doc.metadata for doc in trat])

    # Adicionar a coluna "data" com base no page_content
    df['data'] = [doc.page_content for doc in trat]

    return df

In [4]:

df = retransfromando_pandas(trat)

df

,receita_liquida,resultado_bruto,lucro_liquido,tic,capex_tres_meses,fluxo_caixa_operacional,fluxo_caixa_investimentos,fluxo_caixa_financiamento,aumento_reducao_caixa_equivalentes,preço_lucro,...,patrimonio_liquido,valor_patrimonial_acao,retorno_sobre_patrimonio_liquido_inicial,retorno_sobre_ativo_inicial,margem_bruta,margem_liquida,giro_do_ativo_inicial,alavancagem_financeira,passivo_patrimonio_liquido,data
0,56450.0,19900.0,4150.00,BBDC3,-300.42,10250.0,-9710.0,-5280.0,-4850.0,6.711.15,...,168410.0,0.02,0.104,0.009,0.285,0.071,0.13,12.29,11.29,2024-12-31
1,52500.0,15210.0,4870.00,BBDC3,-10.25,-6280.0,8500.0,-4050.0,-1930.0,9.32,...,167130.0,15.70,0.088,0.008,0.277,0.061,0.13,12.07,11.07,2024-09-30
2,51500.0,16940.0,4120.00,BBDC3,-10.25,28570.0,-6580.0,-13280.0,8790.0,9.96,...,164630.0,15.52,0.078,0.007,0.277,0.054,0.13,12.17,11.17,2024-06-30
3,52770.0,16890.0,4120.00,BBDC3,-205.93,17680.0,2780.0,-1060.0,19220.0,10.16,...,165860.0,15.59,0.080,0.007,0.272,0.053,0.13,11.79,10.79,2024-03-31
4,54110.0,17050.0,1440.00,BBDC3,-393.47,-81010.0,7160.0,8760.0,-65010.0,9.43,...,166330.0,15.63,0.090,0.008,0.271,0.057,0.14,11.59,10.59,2023-12-31
5,56070.0,15920.0,3400.00,BBDC3,-138.21,79570.0,9870.0,-10620.0,78880.0,10.91,...,166230.0,15.62,0.082,0.007,0.271,0.052,0.14,11.40,10.40,2023-09-30
6,56850.0,17140.0,4020.00,BBDC3,6.56,-19740.0,15050.0,-10250.0,-15030.0,10.34,...,166450.0,15.64,0.096,0.009,0.275,0.061,0.14,11.19,10.19,2023-06-30
7,57430.0,17980.0,5400.00,BBDC3,-77.89,21000.0,51520.0,-10960.0,61760.0,7.21,...,162490.0,15.24,0.119,0.011,0.294,0.076,0.14,11.25,10.25,2023-03-31
8,53640.0,18270.0,785.85,BBDC3,-178.48,-32520.0,3860.0,-1860.0,-30350.0,6.27,...,158270.0,14.85,0.140,0.012,0.320,0.090,0.14,11.37,10.37,2022-12-31
9,53140.0,17100.0,5840.00,BBDC3,-368.35,43650.0,-10720.0,13450.0,46420.0,6.44,...,161360.0,15.14,NaN,NaN,0.340,0.119,NaN,11.54,10.54,2022-09-30
10,49280.0,18590.0,7140.00,BBDC3,-172.53,562.2,-17660.0,6290.0,-10660.0,6.17,...,156430.0,14.68,NaN,NaN,0.379,0.134,NaN,11.10,10.10,2022-06-30
11,49860.0,20650.0,7220.00,BBDC3,-1120.00,30070.0,6750.0,4040.0,41380.0,6.39,...,153780.0,14.43,NaN,NaN,0.430,0.138,NaN,11.06,10.06,2022-03-31
12,74840.0,51070.0,16140.00,BBDC3,NaN,NaN,NaN,NaN,NaN,7.91,...,149780.0,15.41,0.159,0.014,0.464,0.153,0.09,11.19,10.19,2021-12-31
13,28540.0,10260.0,6650.00,BBDC3,-215.64,-3710.0,-11720.0,7430.0,-7810.0,6.63,...,147610.0,15.19,0.176,0.017,0.347,0.212,0.08,9.78,8.78,2021-09-30
14,20100.0,17160.0,5970.00,BBDC3,-207.38,-13830.0,-5440.0,-5330.0,-25530.0,9.34,...,146490.0,15.07,0.161,0.016,0.463,0.201,0.08,9.54,8.54,2021-06-30
15,23160.0,6790.0,6150.00,BBDC3,-172.83,-12170.0,-32770.0,-20290.0,-64490.0,10.36,...,144240.0,14.84,0.149,0.016,0.299,0.182,0.09,9.62,8.62,2021-03-31
16,47830.0,30600.0,8800.00,BBDC3,NaN,177880.0,77130.0,-112300.0,145170.0,12.42,...,145620.0,16.42,0.117,0.012,0.404,0.128,0.09,11.02,10.02,2020-12-31
17,22990.0,13740.0,4190.00,BBDC3,-136.83,52790.0,17180.0,-11140.0,56880.0,10.50,...,137460.0,15.50,0.115,0.014,0.014,0.157,0.09,10.26,9.26,2020-09-30
18,18280.0,-1310.0,3510.00,BBDC3,-257.15,54830.0,8130.0,-4500.0,58770.0,10.83,...,135130.0,15.23,0.132,0.016,-0.149,0.172,0.09,9.84,8.84,2020-06-30
19,16100.0,-27380.0,3380.00,BBDC3,-128.49,40370.0,-5460.0,5290.0,41830.0,7.73,...,129550.0,14.60,0.159,0.018,-0.020,0.187,0.10,9.57,8.57,2020-03-31

In [5]:
query = 'Como esta a saude financeira da bbdc3'
response = ChatFundamentalistas(query=query, dados=trat,modelo_llm="deepseek-r1-distill-llama-70b")

In [6]:
response.split('\n\n')

['<think>\nOkay, I need to assess the financial health of BBDC3 based on the provided indicators. Let me start by looking at the key metrics.',
 'First, I notice that the revenue (receita líquida) has been fluctuating. It was around R$56k in 2023, dropped to R$53k in 2022, and then increased again. This inconsistency might indicate some instability in their operations.',
 "Looking at the net income (lucro líquido), it's around R$4k to R$7k, which isn't very high. The net margin (margem líquida) is between 5% and 7%, which is low. This suggests that the company isn't efficiently converting revenue into profit, possibly due to high operating costs or other expenses.",
 "The EBITDA isn't provided, but the operating cash flow (fluxo caixa operacional) is positive in some periods and negative in others. For example, in 2023-12-31, it's R$10k positive, but in 2024-09-30, it's negative. This volatility in cash flow is a concern because it affects the company's ability to meet obligations and invest in growth.",
 "The company's debt levels are high. The leverage ratio (alavancagem financeira) is around 11-12, which is quite elevated. This means they're relying heavily on debt, which can be risky, especially if interest rates rise or if cash flows become unstable. The debt-to-equity ratio is also high, which further points to a risky capital structure.",
 "Looking at cash flow from investments (fluxo caixa investimentos), it's mostly negative, indicating that the company is spending more on investments than it's generating. This could be a sign of capital expenditures without sufficient returns, which isn't sustainable in the long run.",
 "The dividend yield is around 6-7%, which is attractive for income investors. However, with the company's unstable cash flows and high debt, sustaining these dividends might be challenging.",
 "The return on equity (retorno sobre patrimônio líquido) is around 8-14%, which is moderate. It's not exceptional but shows some ability to generate profits from shareholders' equity.",
 "The company's valuation multiples are mixed. The price-to-earnings ratio is high, suggesting the stock might be overvalued. The price-to-sales ratio is also high, which could indicate that the market expects future growth, but given the current margins, that might not materialize.",
 "The asset turnover ratio (giro do ativo) is low at 0.13-0.14, meaning the company isn't efficiently using its assets to generate revenue. This could be a sign of poor asset management or underutilized resources.",
 "Considering all these factors, the company's financial health seems fragile. High debt, volatile cash flows, low profitability margins, and inefficient asset use are significant weaknesses. While the dividend yield is positive, the sustainability is questionable. The high valuation multiples also pose a risk if the company doesn't improve its margins and reduce debt.",
 'Therefore, I would recommend a "hold" position. Investors should monitor the company\'s debt reduction efforts and improvements in profitability before considering a "buy." If the financial situation doesn\'t stabilize, a "sell" might be warranted to avoid potential losses.\n</think>',
 '**Análise da Saúde Financeira da BBDC3**',
 '**Resumo da Análise:**\nA BBDC3 apresenta um perfil financeiro misto, com pontos positivos e negativos que merecem atenção. Embora a receita líquida tenha apresentado uma tendência de crescimento gradual, a margem líquida é relativamente baixa, indicando desafios na gestão de custos. O fluxo de caixa operacional tem sido volátil, com períodos de positivo e negativo, o que pode afetar a capacidade da empresa de honrar seus compromissos. Além disso, a alavancagem financeira elevada e o retorno sobre o patrimônio líquido moderado são fatores que merecem cautela.',
 '**Pontos Fortes:**\n1. **Receita Líquida em Crescimento:** A receita líquida da empresa tem apresentado uma tendência de crescimento ao longo dos últimos anos, indicando uma base de clientes sólida ou um aumento das vendas.\n2. **Dividendo Atrativo:** O dividend yield da BBDC3 é relativamente alto, o que pode atrair investidores que buscam rendimento regular.\n3. **Retorno sobre o Patrimônio Líquido:** O retorno sobre o patrimônio líquido (ROE) é moderado, indicando que a empresa consegue gerar lucros razoáveis com o capital dos acionistas.',
 '**Pontos Fracos:**\n1. **Margem Líquida Baixa:** A margem líquida da empresa é relativamente baixa, o que pode indicar problemas de gestão de custos ou pressão competitiva.\n2. **Fluxo de Caixa Operacional Volátil:** O fluxo de caixa operacional tem apresentado resultados inconsistentes, com períodos de fluxo positivo e negativo, o que pode afetar a capacidade da empresa de manter sua liquidez.\n3. **Alavancagem Financeira Elevada:** A alavancagem financeira da empresa é alta, o que pode ser um risco, especialmente em períodos de instabilidade econômica ou aumento das taxas de juros.\n4. **Passivo Patrimônio Líquido Elevado:** O índice de passivo sobre patrimônio líquido é alto, indicando que a empresa tem uma dívida significativa em relação ao seu patrimônio líquido.',
 '**Recomendação:**\nCom base na análise, recomendo uma posição **"HOLD"** para os investidores da BBDC3. A empresa apresenta alguns pontos positivos, como o crescimento da receita líquida e o retorno sobre o patrimônio líquido moderado, mas também enfrenta desafios significativos, como a margem líquida baixa, o fluxo de caixa operacional volátil e a alavancagem financeira elevada. Os investidores devem monitorar de perto os resultados futuros da empresa, especialmente em relação à gestão de custos e à redução da dívida, antes de tomar uma decisão mais definitiva.',
 '**Tendências Históricas e Implicações Futuras:**\n- **Crescimento da Receita Líquida:** A tendência de crescimento da receita líquida é um sinal positivo, mas a empresa precisa melhorar sua margem líquida para aumentar a rentabilidade.\n- **Fluxo de Caixa Operacional Volátil:** A instabilidade no fluxo de caixa operacional pode afetar a capacidade da empresa de investir em crescimento e pagar dívidas.\n- **Alavancagem Financeira Elevada:** A dívida elevada pode tornar a empresa mais vulnerável a mudanças nas condições econômicas e de mercado.',
 '**Conclusão:**\nA BBDC3 tem um perfil financeiro que requer cautela por parte dos investidores. Embora haja sinais positivos, como o crescimento da receita líquida e o retorno sobre o patrimônio líquido moderado, os desafios relacionados à margem líquida baixa, ao fluxo de caixa operacional volátil e à alavancagem financeira elevada são fatores que não podem ser ignorados. Os investidores devem manter uma posição neutra ("HOLD") e acompanhar de perto os resultados futuros da empresa antes de considerar qualquer mudança em sua posição.']

In [7]:
query = 'Como esta a saude financeira da PETR4'
tic = 'PETR4'
fund = ModeloFundamentos(query=query, ticker=tic)

response, dados = fund.chat_fundamentalistas()

In [8]:
response

In [9]:
retransfromando_pandas(dados)

,receita_liquida,resultado_bruto,ebit,amortizacao,ebitda,lucro_liquido,lucro_por_acao,tic,capex_tres_meses,fluxo_caixa_livre_tres_meses,...,retorno_sobre_capital_investido_inicial,retorno_sobre_patrimonio_liquido_inicial,retorno_sobre_ativo_inicial,margem_bruta,margem_liquida,margem_ebit,giro_do_ativo_inicial,alavancagem_financeira,passivo_patrimonio_liquido,data
0,129580.0,66580.0,46460.0,-16540.0,63000.0,32560.0,2.50,PETR4,-24640.0,38080.0,...,0.171,0.219,0.083,0.518,0.168,0.325,0.49,2.74,1.74,2024-09-30
1,122260.0,61050.0,33540.0,-16360.0,49900.0,-2610.0,- 0.20,PETR4,-15260.0,31910.0,...,0.181,0.212,0.080,0.522,0.158,0.330,0.50,2.83,1.83,2024-06-30
2,117720.0,60700.0,44030.0,-16650.0,60680.0,23700.0,1.82,PETR4,-14050.0,32430.0,...,0.184,0.274,0.113,0.525,0.224,0.353,0.50,2.62,1.62,2024-03-31
3,134260.0,72630.0,39630.0,-20490.0,60120.0,31040.0,2.38,PETR4,-17790.0,39860.0,...,0.208,0.344,0.128,0.527,0.243,0.370,0.52,2.76,1.76,2023-12-31
4,124830.0,66320.0,47550.0,-19480.0,67030.0,26630.0,2.04,PETR4,-15540.0,40990.0,...,0.213,0.368,0.144,0.511,0.255,0.387,0.57,2.66,1.66,2023-09-30
5,113840.0,57680.0,41970.0,-18280.0,60250.0,28780.0,2.21,PETR4,-14390.0,33360.0,...,0.256,0.381,0.156,0.506,0.269,0.403,0.58,2.67,1.67,2023-06-30
6,139070.0,73310.0,60200.0,-17770.0,77970.0,38160.0,2.93,PETR4,-12590.0,41170.0,...,0.303,0.419,0.182,0.521,0.285,0.453,0.64,2.43,1.43,2023-03-31
7,158580.0,76640.0,57810.0,-19460.0,77270.0,43340.0,3.32,PETR4,-18710.0,48870.0,...,0.296,0.486,0.194,0.521,0.294,0.459,0.66,2.69,1.69,2022-12-31
8,170080.0,86840.0,74610.0,-18540.0,93150.0,46100.0,3.53,PETR4,-10230.0,52980.0,...,0.307,0.478,0.181,0.513,0.286,0.478,0.63,2.54,1.54,2022-09-30
9,170960.0,95860.0,96430.0,-18620.0,115050.0,54330.0,4.16,PETR4,-8380.0,63420.0,...,0.302,0.454,0.172,0.509,0.284,0.504,0.60,2.45,1.45,2022-06-30
10,141640.0,74770.0,65400.0,-18500.0,83900.0,44560.0,3.42,PETR4,-12340.0,40490.0,...,0.246,0.479,0.150,0.493,0.295,0.477,0.51,2.30,1.30,2022-03-31
11,134190.0,59050.0,58290.0,-18720.0,77010.0,31500.0,2.42,PETR4,-9410.0,41990.0,...,0.217,0.346,0.108,0.485,0.236,0.466,0.46,2.51,1.51,2021-12-31
12,121590.0,59550.0,66460.0,-17770.0,84230.0,31140.0,2.39,PETR4,-7860.0,47240.0,...,0.233,0.545,0.140,0.511,0.343,0.561,0.41,2.64,1.64,2021-09-30
13,110710.0,57010.0,52180.0,-16470.0,68660.0,42860.0,3.29,PETR4,-7890.0,48670.0,...,0.179,0.422,0.101,0.511,0.299,0.502,0.34,2.64,1.64,2021-06-30
14,86170.0,44030.0,33900.0,-16810.0,50710.0,1170.0,0.09,PETR4,-8980.0,31090.0,...,0.138,0.245,0.058,0.482,0.201,0.456,0.29,3.19,2.19,2021-03-31

In [10]:
query = 'Como esta a saude financeira da bbdc3'
tic = 'BBDC3'
fund = ModeloFundamentos(query=query, ticker=tic)

In [11]:
response = fund.chat_fundamentalistas()

In [12]:
for chunk in response: 
    print(chunk, end="", flush=True)

<generator object RunnableSequence.stream at 0x000002303788A2F0>[Document(metadata={'receita_liquida': 56450.0, 'resultado_bruto': 19900.0, 'lucro_liquido': 4150.0, 'tic': 'BBDC3', 'capex_tres_meses': -300.42, 'fluxo_caixa_operacional': 10250.0, 'fluxo_caixa_investimentos': -9710.0, 'fluxo_caixa_financiamento': -5280.0, 'aumento_reducao_caixa_equivalentes': -4850.0, 'preço_lucro': '6.711.15', 'preço_receita_líquida': '479.34', 'preço_fco': '2.305.20', 'preço_ativo_total': '55.95', 'market_cap_empresa': 121680000.0, 'dividend_yield': 0.0915, 'ativo_total': 2070000.0, 'patrimonio_liquido': 168410.0, 'valor_patrimonial_acao': '0.02', 'retorno_sobre_patrimonio_liquido_inicial': 0.104, 'retorno_sobre_ativo_inicial': 0.009, 'margem_bruta': 0.285, 'margem_liquida': 0.071, 'giro_do_ativo_inicial': '0.13', 'alavancagem_financeira': '12.29', 'passivo_patrimonio_liquido': '11.29'}, page_content='2024-12-31'), Document(metadata={'receita_liquida': 52500.0, 'resultado_bruto': 15210.0, 'lucro_liquido': 4870.0, 'tic': 'BBDC3', 'capex_tres_meses': -10.25, 'fluxo_caixa_operacional': -6280.0, 'fluxo_caixa_investimentos': 8500.0, 'fluxo_caixa_financiamento': -4050.0, 'aumento_reducao_caixa_equivalentes': -1930.0, 'preço_lucro': '9.32', 'preço_receita_líquida': '0.57', 'preço_fco': '-3.30', 'preço_ativo_total': '0.07', 'market_cap_empresa': 144240.0, 'dividend_yield': 0.1076999999999999, 'ativo_total': 2020000.0, 'patrimonio_liquido': 167130.0, 'valor_patrimonial_acao': '15.70', 'retorno_sobre_patrimonio_liquido_inicial': 0.088, 'retorno_sobre_ativo_inicial': 0.008, 'margem_bruta': 0.277, 'margem_liquida': 0.061, 'giro_do_ativo_inicial': '0.13', 'alavancagem_financeira': '12.07', 'passivo_patrimonio_liquido': '11.07'}, page_content='2024-09-30'), Document(metadata={'receita_liquida': 51500.0, 'resultado_bruto': 16940.0, 'lucro_liquido': 4120.0, 'tic': 'BBDC3', 'capex_tres_meses': -10.25, 'fluxo_caixa_operacional': 28570.0, 'fluxo_caixa_investimentos': -6580.0, 'fluxo_caixa_financiamento': -13280.0, 'aumento_reducao_caixa_equivalentes': 8790.0, 'preço_lucro': '9.96', 'preço_receita_líquida': '0.54', 'preço_fco': '2.90', 'preço_ativo_total': '0.06', 'market_cap_empresa': 137260.0, 'dividend_yield': 0.0958, 'ativo_total': 2000000.0, 'patrimonio_liquido': 164630.0, 'valor_patrimonial_acao': '15.52', 'retorno_sobre_patrimonio_liquido_inicial': 0.078, 'retorno_sobre_ativo_inicial': 0.007, 'margem_bruta': 0.277, 'margem_liquida': 0.054, 'giro_do_ativo_inicial': '0.13', 'alavancagem_financeira': '12.17', 'passivo_patrimonio_liquido': '11.17'}, page_content='2024-06-30'), Document(metadata={'receita_liquida': 52770.0, 'resultado_bruto': 16890.0, 'lucro_liquido': 4120.0, 'tic': 'BBDC3', 'capex_tres_meses': -205.93, 'fluxo_caixa_operacional': 17680.0, 'fluxo_caixa_investimentos': 2780.0, 'fluxo_caixa_financiamento': -1060.0, 'aumento_reducao_caixa_equivalentes': 19220.0, 'preço_lucro': '10.16', 'preço_receita_líquida': '0.53', 'preço_fco': '-37.63', 'preço_ativo_total': '0.07', 'market_cap_empresa': 139560.0, 'dividend_yield': 0.0817, 'ativo_total': 1960000.0, 'patrimonio_liquido': 165860.0, 'valor_patrimonial_acao': '15.59', 'retorno_sobre_patrimonio_liquido_inicial': 0.08, 'retorno_sobre_ativo_inicial': 0.007, 'margem_bruta': 0.272, 'margem_liquida': 0.053, 'giro_do_ativo_inicial': '0.13', 'alavancagem_financeira': '11.79', 'passivo_patrimonio_liquido': '10.79'}, page_content='2024-03-31'), Document(metadata={'receita_liquida': 54110.0, 'resultado_bruto': 17050.0, 'lucro_liquido': 1440.0, 'tic': 'BBDC3', 'capex_tres_meses': -393.47, 'fluxo_caixa_operacional': -81010.0, 'fluxo_caixa_investimentos': 7160.0, 'fluxo_caixa_financiamento': 8760.0, 'aumento_reducao_caixa_equivalentes': -65010.00000000001, 'preço_lucro': '9.43', 'preço_receita_líquida': '0.53', 'preço_fco': '-756.70', 'preço_ativo_total': '0.07', 'market_cap_empresa': 141480.0, 'dividend_yield': 0.0788, 'ativo_total': 1930000.0, 'patrimonio_liquido': 166330.0, 'valor_patrimonial_acao': '15.63', 'retorno_sobre_patrimonio_liquido_inicial': 0.09, 'retorno_sobre_ativo_inicial': 0.008, 'margem_bruta': 0.271, 'margem_liquida': 0.057, 'giro_do_ativo_inicial': '0.14', 'alavancagem_financeira': '11.59', 'passivo_patrimonio_liquido': '10.59'}, page_content='2023-12-31'), Document(metadata={'receita_liquida': 56070.0, 'resultado_bruto': 15920.0, 'lucro_liquido': 3400.0, 'tic': 'BBDC3', 'capex_tres_meses': -138.21, 'fluxo_caixa_operacional': 79570.0, 'fluxo_caixa_investimentos': 9870.0, 'fluxo_caixa_financiamento': -10620.0, 'aumento_reducao_caixa_equivalentes': 78880.0, 'preço_lucro': '10.91', 'preço_receita_líquida': '0.57', 'preço_fco': '2.97', 'preço_ativo_total': '0.08', 'market_cap_empresa': 152910.0, 'dividend_yield': 0.0667, 'ativo_total': 1900000.0, 'patrimonio_liquido': 166230.0, 'valor_patrimonial_acao': '15.62', 'retorno_sobre_patrimonio_liquido_inicial': 0.082, 'retorno_sobre_ativo_inicial': 0.007, 'margem_bruta': 0.271, 'margem_liquida': 0.052, 'giro_do_ativo_inicial': '0.14', 'alavancagem_financeira': '11.40', 'passivo_patrimonio_liquido': '10.40'}, page_content='2023-09-30'), Document(metadata={'receita_liquida': 56850.0, 'resultado_bruto': 17140.0, 'lucro_liquido': 4020.0, 'tic': 'BBDC3', 'capex_tres_meses': 6.56, 'fluxo_caixa_operacional': -19740.0, 'fluxo_caixa_investimentos': 15050.0, 'fluxo_caixa_financiamento': -10250.0, 'aumento_reducao_caixa_equivalentes': -15030.0, 'preço_lucro': '10.34', 'preço_receita_líquida': '0.63', 'preço_fco': '12.60', 'preço_ativo_total': '0.08', 'market_cap_empresa': 166110.0, 'dividend_yield': 0.0613, 'ativo_total': 1860000.0, 'patrimonio_liquido': 166450.0, 'valor_patrimonial_acao': '15.64', 'retorno_sobre_patrimonio_liquido_inicial': 0.096, 'retorno_sobre_ativo_inicial': 0.009, 'margem_bruta': 0.275, 'margem_liquida': 0.061, 'giro_do_ativo_inicial': '0.14', 'alavancagem_financeira': '11.19', 'passivo_patrimonio_liquido': '10.19'}, page_content='2023-06-30'), Document(metadata={'receita_liquida': 57430.0, 'resultado_bruto': 17980.0, 'lucro_liquido': 5400.0, 'tic': 'BBDC3', 'capex_tres_meses': -77.89, 'fluxo_caixa_operacional': 21000.0, 'fluxo_caixa_investimentos': 51520.0, 'fluxo_caixa_financiamento': -10960.0, 'aumento_reducao_caixa_equivalentes': 61760.0, 'preço_lucro': '7.21', 'preço_receita_líquida': '0.55', 'preço_fco': '4.05', 'preço_ativo_total': '0.07', 'market_cap_empresa': 141100.0, 'dividend_yield': 0.0724, 'ativo_total': 1830000.0, 'patrimonio_liquido': 162490.0, 'valor_patrimonial_acao': '15.24', 'retorno_sobre_patrimonio_liquido_inicial': 0.119, 'retorno_sobre_ativo_inicial': 0.011, 'margem_bruta': 0.294, 'margem_liquida': 0.076, 'giro_do_ativo_inicial': '0.14', 'alavancagem_financeira': '11.25', 'passivo_patrimonio_liquido': '10.25'}, page_content='2023-03-31'), Document(metadata={'receita_liquida': 53640.0, 'resultado_bruto': 18270.0, 'lucro_liquido': 785.85, 'tic': 'BBDC3', 'capex_tres_meses': -178.48, 'fluxo_caixa_operacional': -32520.000000000004, 'fluxo_caixa_investimentos': 3860.0, 'fluxo_caixa_financiamento': -1860.0, 'aumento_reducao_caixa_equivalentes': -30350.0, 'preço_lucro': '6.27', 'preço_receita_líquida': '0.56', 'preço_fco': '3.15', 'preço_ativo_total': '0.07', 'market_cap_empresa': 139290.0, 'dividend_yield': 0.074, 'ativo_total': 1800000.0, 'patrimonio_liquido': 158270.0, 'valor_patrimonial_acao': '14.85', 'retorno_sobre_patrimonio_liquido_inicial': 0.14, 'retorno_sobre_ativo_inicial': 0.012, 'margem_bruta': 0.32, 'margem_liquida': 0.09, 'giro_do_ativo_inicial': '0.14', 'alavancagem_financeira': '11.37', 'passivo_patrimonio_liquido': '10.37'}, page_content='2022-12-31'), Document(metadata={'receita_liquida': 53140.0, 'resultado_bruto': 17100.0, 'lucro_liquido': 5840.0, 'tic': 'BBDC3', 'capex_tres_meses': -368.35, 'fluxo_caixa_operacional': 43650.0, 'fluxo_caixa_investimentos': -10720.0, 'fluxo_caixa_financiamento': 13450.0, 'aumento_reducao_caixa_equivalentes': 46420.0, 'preço_lucro': '6.44', 'preço_receita_líquida': '0.77', 'preço_fco': '0.69', 'preço_ativo_total': '0.09', 'market_cap_empresa': 183190.0, 'dividend_yield': 0.0364, 'ativo_total': 1860000.0, 'patrimonio_liquido': 161360.0, 'valor_patrimonial_acao': '15.14', 'retorno_sobre_patrimonio_liquido_inicial': nan, 'retorno_sobre_ativo_inicial': nan, 'margem_bruta': 0.34, 'margem_liquida': 0.119, 'giro_do_ativo_inicial': nan, 'alavancagem_financeira': '11.54', 'passivo_patrimonio_liquido': '10.54'}, page_content='2022-09-30'), Document(metadata={'receita_liquida': 49280.0, 'resultado_bruto': 18590.0, 'lucro_liquido': 7140.0, 'tic': 'BBDC3', 'capex_tres_meses': -172.53, 'fluxo_caixa_operacional': 562.2, 'fluxo_caixa_investimentos': -17660.0, 'fluxo_caixa_financiamento': 6290.0, 'aumento_reducao_caixa_equivalentes': -10660.0, 'preço_lucro': '6.17', 'preço_receita_líquida': '0.82', 'preço_fco': '0.81', 'preço_ativo_total': '0.09', 'market_cap_empresa': 178290.0, 'dividend_yield': 0.0375, 'ativo_total': 1740000.0, 'patrimonio_liquido': 156430.0, 'valor_patrimonial_acao': '14.68', 'retorno_sobre_patrimonio_liquido_inicial': nan, 'retorno_sobre_ativo_inicial': nan, 'margem_bruta': 0.379, 'margem_liquida': 0.134, 'giro_do_ativo_inicial': nan, 'alavancagem_financeira': '11.10', 'passivo_patrimonio_liquido': '10.10'}, page_content='2022-06-30'), Document(metadata={'receita_liquida': 49860.0, 'resultado_bruto': 20650.0, 'lucro_liquido': 7220.0, 'tic': 'BBDC3', 'capex_tres_meses': -1120.0, 'fluxo_caixa_operacional': 30070.0, 'fluxo_caixa_investimentos': 6750.0, 'fluxo_caixa_financiamento': 4040.0, 'aumento_reducao_caixa_equivalentes': 41380.0, 'preço_lucro': '6.39', 'preço_receita_líquida': '0.88', 'preço_fco': '0.86', 'preço_ativo_total': '0.09', 'market_cap_empresa': 172050.0, 'dividend_yield': 0.0571, 'ativo_total': 1700000.0, 'patrimonio_liquido': 153780.0, 'valor_patrimonial_acao': '14.43', 'retorno_sobre_patrimonio_liquido_inicial': nan, 'retorno_sobre_ativo_inicial': nan, 'margem_bruta': 0.43, 'margem_liquida': 0.138, 'giro_do_ativo_inicial': nan, 'alavancagem_financeira': '11.06', 'passivo_patrimonio_liquido': '10.06'}, page_content='2022-03-31'), Document(metadata={'receita_liquida': 74840.0, 'resultado_bruto': 51070.0, 'lucro_liquido': 16140.0, 'tic': 'BBDC3', 'capex_tres_meses': nan, 'fluxo_caixa_operacional': nan, 'fluxo_caixa_investimentos': nan, 'fluxo_caixa_financiamento': nan, 'aumento_reducao_caixa_equivalentes': nan, 'preço_lucro': '7.91', 'preço_receita_líquida': '1.21', 'preço_fco': '-1.80', 'preço_ativo_total': '0.11', 'market_cap_empresa': 202070.0, 'dividend_yield': 0.0492, 'ativo_total': 1680000.0, 'patrimonio_liquido': 149780.0, 'valor_patrimonial_acao': '15.41', 'retorno_sobre_patrimonio_liquido_inicial': 0.159, 'retorno_sobre_ativo_inicial': 0.014, 'margem_bruta': 0.464, 'margem_liquida': 0.153, 'giro_do_ativo_inicial': '0.09', 'alavancagem_financeira': '11.19', 'passivo_patrimonio_liquido': '10.19'}, page_content='2021-12-31'), Document(metadata={'receita_liquida': 28540.0, 'resultado_bruto': 10260.0, 'lucro_liquido': 6650.0, 'tic': 'BBDC3', 'capex_tres_meses': -215.64, 'fluxo_caixa_operacional': -3710.0, 'fluxo_caixa_investimentos': -11720.0, 'fluxo_caixa_financiamento': 7430.0, 'aumento_reducao_caixa_equivalentes': -7810.0, 'preço_lucro': '6.63', 'preço_receita_líquida': '1.40', 'preço_fco': '-2.84', 'preço_ativo_total': '0.11', 'market_cap_empresa': 172920.0, 'dividend_yield': 0.0635, 'ativo_total': 1440000.0, 'patrimonio_liquido': 147610.0, 'valor_patrimonial_acao': '15.19', 'retorno_sobre_patrimonio_liquido_inicial': 0.176, 'retorno_sobre_ativo_inicial': 0.017, 'margem_bruta': 0.347, 'margem_liquida': 0.212, 'giro_do_ativo_inicial': '0.08', 'alavancagem_financeira': '9.78', 'passivo_patrimonio_liquido': '8.78'}, page_content='2021-09-30'), Document(metadata={'receita_liquida': 20100.0, 'resultado_bruto': 17160.0, 'lucro_liquido': 5970.0, 'tic': 'BBDC3', 'capex_tres_meses': -207.38, 'fluxo_caixa_operacional': -13830.0, 'fluxo_caixa_investimentos': -5440.0, 'fluxo_caixa_financiamento': -5330.0, 'aumento_reducao_caixa_equivalentes': -25530.0, 'preço_lucro': '9.34', 'preço_receita_líquida': '1.87', 'preço_fco': '-2.924.69', 'preço_ativo_total': '0.15', 'market_cap_empresa': 220880.0, 'dividend_yield': 0.0507, 'ativo_total': 1400000.0, 'patrimonio_liquido': 146490.0, 'valor_patrimonial_acao': '15.07', 'retorno_sobre_patrimonio_liquido_inicial': 0.161, 'retorno_sobre_ativo_inicial': 0.016, 'margem_bruta': 0.463, 'margem_liquida': 0.201, 'giro_do_ativo_inicial': '0.08', 'alavancagem_financeira': '9.54', 'passivo_patrimonio_liquido': '8.54'}, page_content='2021-06-30'), Document(metadata={'receita_liquida': 23160.0, 'resultado_bruto': 6790.0, 'lucro_liquido': 6150.0, 'tic': 'BBDC3', 'capex_tres_meses': -172.83, 'fluxo_caixa_operacional': -12170.0, 'fluxo_caixa_investimentos': -32770.0, 'fluxo_caixa_financiamento': -20290.0, 'aumento_reducao_caixa_equivalentes': -64489.99999999999, 'preço_lucro': '10.36', 'preço_receita_líquida': '1.88', 'preço_fco': '2.92', 'preço_ativo_total': '0.14', 'market_cap_empresa': 215730.0, 'dividend_yield': 0.0275, 'ativo_total': 1390000.0, 'patrimonio_liquido': 144240.0, 'valor_patrimonial_acao': '14.84', 'retorno_sobre_patrimonio_liquido_inicial': 0.149, 'retorno_sobre_ativo_inicial': 0.016, 'margem_bruta': 0.299, 'margem_liquida': 0.182, 'giro_do_ativo_inicial': '0.09', 'alavancagem_financeira': '9.62', 'passivo_patrimonio_liquido': '8.62'}, page_content='2021-03-31')]

# Sentimento

In [13]:
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--disable-features=NetworkService")
chrome_options.add_argument("--window-size=1920x1080")
chrome_options.add_argument("--disable-features=VizDisplayCompositor")

dados_yahoo = DadosNoticiasBuscadorYahoo(acao='PETR4', options=chrome_options)

In [14]:
links = dados_yahoo.get_news(number_paginas=1)["links"]

In [15]:
links

['https://www.infomoney.com.br/mercados/petrobras-petr4-reduz-preco-do-diesel-em-46-nas-refinarias-diz-presidente/',
 'https://www.infomoney.com.br/mercados/petrobras-petr4-nomeia-aloisio-macario-para-conselho-de-administracao/',
 'https://einvestidor.estadao.com.br/ultimas/petrobras-petr3-petr4-ajuste-preco-diesel-itau-bba-acoes/',
 'https://einvestidor.estadao.com.br/mercado/petrobras-petr4-tarifas-trump-petroleo-russo/',
 'https://br.investing.com/analysis/ibovespa-hoje-winj25-wdok25-petr4-vale3-e-mais-cvcb3-62-200469594',
 'https://www.infomoney.com.br/mercados/ibovespa-hoje-bolsa-de-valores-ao-vivo-01042025/',
 'https://einvestidor.estadao.com.br/ultimas/petrobras-petr3-petr4-preco-diesel-magda/',
 'https://einvestidor.estadao.com.br/ultimas/citi-reducao-diesel-petrobras-petr4-impacto/',
 'https://valorinveste.globo.com/mercados/renda-variavel/empresas/noticia/2025/03/26/petrobras-petr4-impulsiona-ibovespa-prio-prio3-e-brava-brav3-disparam.ghtml',
 'https://einvestidor.estadao.com.br/ultimas/petrobras-petr3-petr4-acordo-emergencial-azul-azul4-voepass/']

In [16]:
ticker = 'BBDC3'
from dotenv import load_dotenv
load_dotenv()
import os

api_secret_groq = os.getenv("GROQ_API_KEY")
api_secret_serper = os.getenv("SERPER_API_KEY")

dados_google = TratarDadosNoticias(ticker, chrome_options, api_secret_groq, api_secret_serper)

In [17]:
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--disable-features=NetworkService")
chrome_options.add_argument("--window-size=1920x1080")
chrome_options.add_argument("--disable-features=VizDisplayCompositor")

ticker = 'BBDC3'
news_tratado = TratarDadosNoticias(ticker, chrome_options, api_secret_groq, api_secret_serper)
dados_new = news_tratado.clean_chat_html_bs4()

Sem mais páginas!

In [18]:
query = f'Qual é o sentimento sobre as notícias sobre a {ticker}'
dados_noticia = ChatSentimento(query=query, noticia=dados_new, modelo_llm="deepseek-r1-distill-llama-70b")

In [19]:
dados_noticia.split('\n\n')

['<think>\nOkay, I need to evaluate the sentiment of recent news about BBDC3, which is Bradesco. Let me go through each news article one by one.',
 'First article: It talks about companies paying dividends, including Itaú, Itaúsa, and others. It mentions that these payments are good for passive income investors. This seems positive because dividend payments indicate financial health and return to shareholders. So, sentiment is positive, maybe around +0.8.',
 "Second article: B3 announces changes in the Ibovespa index. Direcional is added, while Automob and LWSA are excluded. This is more about index rebalancing. Not directly about Bradesco, so I'll mark it as neutral with a score of 0.",
 "Third article: Discusses the Ibovespa's performance affected by foreign capital and liquidity. It's a mixed situation with some concerns about investor sentiment. This might be slightly negative, so maybe -0.2.",
 "Fourth article: Highlights the Ibovespa's performance in March, with some stocks rising and others falling. Bradesco isn't directly mentioned, so another neutral with 0.",
 'Fifth article: Talks about the Ibovespa closing high, helped by major stocks like Bradesco. Positive mention of Bradesco contributing to the index, so this is positive, around +0.7.',
 'Sixth article: Ibovespa renews its yearly high but with some gain reduction. Still, Bradesco is among the top performers, so positive, maybe +0.6.',
 'Seventh article: The Ibovespa is affected by tariff announcements from the US. This creates uncertainty, which is negative. Sentiment here is -0.5.',
 "Eighth article: Discusses the Ibovespa's future depending on US tariffs. Bradesco isn't directly mentioned, so neutral with 0.",
 'Ninth article: The Ibovespa drops due to profit-taking and tariffs. Negative impact, so -0.4.',
 "Tenth article: Talks about dividends, including Bradesco. Positive as it's paying dividends, so +0.8.",
 "Now, calculating the average sentiment score: Let's add them up. ",
 'Positive scores: 0.8 + 0.7 + 0.6 + 0.8 = 2.9\nNegative scores: -0.2 -0.5 -0.4 = -1.1\nNeutral scores: 0 + 0 + 0 = 0',
 'Total sum: 2.9 -1.1 = 1.8',
 'Average: 1.8 / 10 = 0.18',
 'Since 0.18 is between -0.3 and +0.3, the overall sentiment is neutral. So, the recommendation is caution.\n</think>',
 '**Sentimento Geral das Notícias sobre BBDC3 (Bradesco):**',
 'Após analisar as notícias recentes sobre a BBDC3, calculamos a pontuação de sentimento de cada notícia e encontramos a seguinte distribuição:',
 '1. **Notícia 1**: Positivo, pontuação +0,8  \n2. **Notícia 2**: Neutra, pontuação 0  \n3. **Notícia 3**: Negativo, pontuação -0,2  \n4. **Notícia 4**: Neutra, pontuação 0  \n5. **Notícia 5**: Positivo, pontuação +0,7  \n6. **Notícia 6**: Positivo, pontuação +0,6  \n7. **Notícia 7**: Negativo, pontuação -0,5  \n8. **Notícia 8**: Neutra, pontuação 0  \n9. **Notícia 9**: Negativo, pontuação -0,4  \n10. **Notícia 10**: Positivo, pontuação +0,8  ',
 '**Cálculo do Índice de Sentimento Geral:**  \nA soma das pontuações é:  \nPositivo: 0,8 + 0,7 + 0,6 + 0,8 = 2,9  \nNegativo: -0,2 -0,5 -0,4 = -1,1  \nNeutra: 0 + 0 + 0 = 0  ',
 'Total: 2,9 -1,1 = 1,8  \nMédia: 1,8 / 10 = 0,18  ',
 '**Conclusão:**  \nO índice de sentimento geral é de 0,18, que está entre -0,3 e +0,3. Portanto, o sentimento é **neutro**, e a recomendação é de **cautela** para investidores.']

In [20]:
ticker = 'BBDC3'
query = f'Qual é o sentimento sobre as notícias sobre a {ticker}'
sent = ModeloSentimento(query=query, acao=ticker)

response = sent.chat_sentimento()

Sem mais páginas!

In [21]:
for chunk in response: 
    print(chunk, end="", flush=True)

<generator object RunnableSequence.stream at 0x00000230382A53F0>
New notice
 veja lista - InfoMoney
Itaú, Itaúsa e mais 23 empresas pagam bilhões em dividendos em abril; veja lista
Os valores dos pagamentos chegam a R$ 2,08 por ação
Investidores interessados em renda passiva terão um abril recheado de proventos. Pelo menos 25 empresas listadas na B3 vão depositar dividendos e juros sobre capital próprio (JCP) ao longo do mês, segundo levantamento da Quantum Finance.A Itaúsa (ITSA4; ITSA3) dará o pontapé inicial nesta terça-feira (1º), com o pagamento da segunda parcela de um total de R$ 8 bilhões anunciados pelo Conselho de Administração em fevereiro. O montante será destinado aos acionistas que estavam nos registros até 28 de fevereiro.
Leia mais: Itaúsa (ITSA4) vai pagar R$8 bi em proventos e aumentar capital em
New notice
ação e 2 saídas - InfoMoney
B3 divulga 1ª prévia da nova carteira do Ibovespa com entrada de 1 ação e 2 saídas
As ações da construtora Direcional foram incluídas, enquanto Automob e LWSA saíram
Painel na B3, em São Paulo, Brasil, em 17 de dezembro (Bloomberg)
A B3 divulgou na manhã desta terça-feira (1º) a primeira prévia da carteira teórica do Ibovespa para o período de maio a agosto de 2025. A segunda e terceira prévias do índice serão publicadas nos dias 15 e 30 de abril. A nova carteira passa a valer a partir do dia 5 de maio.As ações da construtora Direcional (DIRR3) foram incluídas, com peso de 0,166%. Os papéis da Automob (AMOB3) e LWSA (LWSA3), por sua vez, foram excluídos. Assim, se a nova composição for confirmada, o Ibovespa será
New notice
 mercados. Entenda o que está emperrando a bolsa
Saldo do Dia: O Ibovespa avançou com o capital estrangeiro ainda fugindo do risco-Trump nos EUA. Mas a liquidez da carteira seguiu fraca, no menor patamar em cinco anos. Com a apatia do investidor doméstico, por quanto tempo o fluxo de recursos para o Brasil vai se sustentar?
A próxima quarta-feira, dia 2 de abril, marca o dia D para os mercados. É nesta data, daqui uma semana, que a tarifação recíproca decretada pelo presidente dos Estados Unidos, Donald Trump, deve entrar em vigor.
Desde que foi anunciada, Trump já ameaçou revisar a proposta algumas vezes.
Ora mais abrangente e rigorosa contra seus alvos, ora possivelmente restrita a alguns setores ou focada em alguns parceiros comerciais.
New notice
Ibovespa em março - InfoMoney
5 ações sobem mais de 30% e só 4 caem mais de 6%: os destaques do Ibovespa em março
Minerva foi a maior alta do mês, enquanto Natura&Co registrou a maior queda do período
O Ibovespa caiu mais de 1% nesta segunda-feira (31), contaminado pela aversão ao risco no exterior, em meio ao esperado anúncio de novas tarifas pelo presidente dos Estados Unidos. Contudo, no mês, o benchmark da Bolsa brasileira teve ganhos de 6%, guiado por companhias como Magalu (MGLU3), Cogna (COGN3) e frigoríficos como Minerva (BEEF3), JBS (JBSS3) e Marfrig (MRFG3). As ações das 5 companhias tiveram ganhos superiores a 30%.Já do lado das perdas, destaque para a queda de Natura (NTCO3), com baixa de mais de 20%. Contudo, apenas 4 ativos re
New notice
o financeiro
Ibovespa hoje: Braskem (BRKM5) salta com acordo no radar e Automob (AMOB3) derrete
Principal índice da B3 fechou no maior nível desde o dia 2 de outubro, com ajuda de ações de peso
O Ibovespa é o principal índice da B3, a Bolsa de Valores brasileira. Foto: Divulgação/B3
O Ibovespa hoje fechou em alta, no patamar mais elevado do ano, com a ajuda de ações de grande peso para a carteira do índice, como Vale (VALE3), Petrobras (PETR3;PETR4) e Bradesco (BBDC3;BBDC4). A principal referência da B3 terminou esta quarta-feira (26) em valorização de 0,34% aos 132.519,63 pontos, depois de oscilar entre máxima a 132.983,92 pontos e mínima a 132.068,02 pontos. O volume negociado foi de R$ 22 bilhões. Esse foi o maior nível de encerramento d
New notice
- InfoMoney
Ibovespa renova máxima do ano, mas diminui ganhos e fecha em alta de 0,57%
Ata do Copom, commodities, e rotação no mercado estiveram no radar do mercado na sessão desta terça
O Ibovespa voltou a renovar a máxima do ano, durante a sessão, e parecia a caminho de encerrar o dia também no maior nível desde 2 de outubro, mas perdeu parte da força em direção ao fechamento em alta de 0,57%, aos 132.067,69 pontos, com giro a R$ 19,7 bilhões. Entre a mínima e a máxima, foi dos 131.325,36 aos 133.471,08 pontos, saindo de abertura aos 131.326,63.Na semana, ainda não neutraliza perdas (-0,21%), com ganhos no mês a 7,55% e no ano a 9,80%. O dia foi de alta bem espalhada pelas ações de maior peso, como Vale (VALE3; ON +0,33%), Petrobras (PETR
New notice
ão para a bolsa brasileira
Saldo do Dia: O Ibovespa passou ileso pela sinalização mais dura da ata do Copom sobre o ciclo de apertos nos juros. Mesmo sem um fim à vista, o índice recuperou os 132 mil pontos com a alta generalizada da carteira. Só que algo ainda entrou no seu caminho...
Mesmo que este ainda seja o enigma central para o mercado brasileiro, foi profundamente ignorado por investidores na sessão desta terça-feira (25).
Embora o Comitê de Política Monetária (Copom) do Banco Central (BC) não tenha se comprometido com um fim no ciclo de apertos na taxa básica de juros, o otimismo marcou a sessão de hoje na bolsa brasileira.
O Ibovespa avançou 0,57% e recuperou os 132 mil pontos. Durante a sessão, chegou aos 133.471 pontos na máxima
New notice
4. O que será da bolsa de agora em diante?
Saldo do Dia: Com alta acumulada em 10,7% neste ano, o índice tem se descolado do movimento no exterior. Mas seu futuro ainda depende de se o Brasil vai ou não passar incólume pelo tarifaço dos EUA que será anunciado em 2 de abril. Desta e de outras discussões mais...
O principal índice da bolsa do Brasil se recuperou nesta quinta (27) do tombo de 10,36% em 2024. Enfim!
O Ibovespa está com ganho acumulado em 10,7% neste ano, tendo alcançado os 133 mil pontos hoje. Nesta sessão, avançou 0,47%. Na semana, o ganho é de 0,61%. No mês de março, está com saldo positivo de 8,43%.
Foi por pouco. Na reta final do pregão, o índice perdeu tração e reduziu a margem de alta. Mais cedo, chegou a flertar com a id
New notice
sde fevereiro - InfoMoney
Tarifas derrubam Ibovespa aos 131 mil e marcam 1ª semana negativa desde fevereiro
Ruídos gerados pelo governo Trump criam um panorama de permanente instabilidade e maior incerteza
Após ter fechado o dia anterior aos 133 mil pontos pela primeira vez no ano, e no maior nível desde o começo de outubro, o Ibovespa passou na sexta-feira, 28, por uma realização de lucros na ultima sessão da semana, e penúltima do mês, retrocedendo à casa dos 131 mil. Nesta sexta, oscilou dos 131.315,07 aos 133.143,44 pontos, na máxima correspondente ao nível de abertura. Ao fim, mostrava perda de 0,94%, aos 131.902,18 pontos com giro a R$ 18,3 bilhões.Na semana, recuou 0,33%, no que foi o seu primeiro agregado negativo desde o intervalo
New notice
 principais notícias do mercado financeiro
Dividendos da semana: Itaú (ITUB4), Bradesco (BBDC4) e Ambev (ABEV3) pagam acionistas; veja lista completa
Entre as principais pagadoras de dividendos da semana, estão Bradesco, Itaúsa e Unipar. Confira quem remunera o acionista até sexta-feira (4)
Distribuição de proventos se tornou um dos aspectos mais considerados pelo investidor ao decidir comprar ações. São 7 empresas que pagam dividendos na semana. (Foto: Envato Elements)
Diversas empresas anunciaram pagamentos de dividendos e juros sobre capital próprio (JCP) para os próximos dias. Entre as principais pagadoras de proventos da semana, estão Bradesco (BBDC4), Itaúsa (ITSA4) e Unipar (UNIP6). Esta última vai remunerar seus acionistas com o mai

# Analise tecnica

In [22]:
ticker = 'BBDC3'
trat_indi = TratandoDadosIndicadores(ticker=ticker, periodo= "18Y", intervalo="1mo" )

In [23]:
dados_indicadores =   trat_indi.indicadores_data_loader()
dados_indicadores

[Document(metadata={'20 period SMA': 11.826822996139526, '100 period SMA': 12.346338458061219, '200 period SMA': 8.903815943002702, '14 period RSI': 52.00525275269524, 'MACD': -0.3659944037101166, 'SIGNAL': -0.4829874890037802, 'BB_UPPER': 14.122697854603778, 'BB_MIDDLE': 11.826822996139526, 'BB_LOWER': 9.530948137675274, 'pivot': 10.985268632563406, 's1': 10.59765699659199, 's2': 10.368613782612695, 's3': 9.981002146641279, 's4': 9.593390510669863, 'r1': 11.214311846542701, 'r2': 11.601923482514117, 'r3': 11.830966696493412, 'r4': 12.060009910472708, 'VWAP.': 10.498134759587956, '14 period ADX.': 12.943187799268424, 0: 10.040221943764793}, page_content='2023-11-01'),
 Document(metadata={'20 period SMA': 11.899754953384399, '100 period SMA': 12.409823999404907, '200 period SMA': 8.950630935430526, '14 period RSI': 55.47136488059653, 'MACD': -0.19871200922692545, 'SIGNAL': -0.4261323930484092, 'BB_UPPER': 14.313699741736162, 'BB_MIDDLE': 11.899754953384399, 'BB_LOWER': 9.485810165032635, 'pivot': 12.097313647994504, 's1': 11.323955942278852, 's2': 10.050709583532312, 's3': 9.27735187781666, 's4': 8.503994172101008, 'r1': 13.370560006741044, 'r2': 14.143917712456696, 'r3': 15.417164071203237, 'r4': 16.69041042994978, 'VWAP.': 10.51919184438224, '14 period ADX.': 13.574611263628675, 0: 10.17157554676189}, page_content='2023-12-01'),
 Document(metadata={'20 period SMA': 11.82892804145813, '100 period SMA': 12.465098485946655, '200 period SMA': 8.988539375066757, '14 period RSI': 50.04024545935074, 'MACD': -0.16567113333359984, 'SIGNAL': -0.37404014110544737, 'BB_UPPER': 14.104911013279208, 'BB_MIDDLE': 11.82892804145813, 'BB_LOWER': 9.552945069637053, 'pivot': 13.300759862698436, 's1': 12.670615003076009, 's2': 11.843182177477704, 's3': 11.213037317855276, 's4': 10.582892458232848, 'r1': 14.12819268829674, 'r2': 14.758337547919169, 'r3': 15.585770373517473, 'r4': 16.413203199115777, 'VWAP.': 10.533344276337115, '14 period ADX.': 13.808201071683502, 0: 10.397135297295428}, page_content='2024-01-01'),
 Document(metadata={'20 period SMA': 11.797445392608642, '100 period SMA': 12.508614978790284, '200 period SMA': 9.02036044716835, '14 period RSI': 45.38745617209004, 'MACD': -0.23539759728926946, 'SIGNAL': -0.3463116323422118, 'BB_UPPER': 14.101198271075694, 'BB_MIDDLE': 11.797445392608642, 'BB_LOWER': 9.49369251414159, 'pivot': 12.69426556078548, 's1': 11.715948475895242, 's2': 11.190997865791948, 's3': 10.21268078090171, 's4': 9.234363696011473, 'r1': 13.219216170888775, 'r2': 14.197533255779012, 'r3': 14.722483865882307, 'r4': 15.247434475985601, 'VWAP.': 10.547981105181671, '14 period ADX.': 12.91524684859898, 0: 10.609161462796955}, page_content='2024-02-01'),
 Document(metadata={'20 period SMA': 11.775382328033448, '100 period SMA': 12.554517784118651, '200 period SMA': 9.053512774705887, '14 period RSI': 47.155997406467556, 'MACD': -0.25475652331793164, 'SIGNAL': -0.3280006105373558, 'BB_UPPER': 14.084718346565847, 'BB_MIDDLE': 11.775382328033448, 'BB_LOWER': 9.46604630950105, 'pivot': 11.642743667574868, 's1': 10.206436899544594, 's2': 9.39422183680891, 's3': 7.957915068778636, 's4': 6.521608300748362, 'r1': 12.454958730310551, 'r2': 13.891265498340825, 'r3': 14.703480561076509, 'r4': 15.515695623812192, 'VWAP.': 10.555957250832718, '14 period ADX.': 12.086075164393408, 0: 10.80846605836839}, page_content='2024-03-01'),
 Document(metadata={'20 period SMA': 11.680086660385133, '100 period SMA': 12.606847066879272, '200 period SMA': 9.08540092587471, '14 period RSI': 45.881452517479666, 'MACD': -0.2929779677510531, 'SIGNAL': -0.32099608198009527, 'BB_UPPER': 13.931892427960683, 'BB_MIDDLE': 11.680086660385133, 'BB_LOWER': 9.428280892809582, 'pivot': 11.3045762963159, 's1': 11.01157205792659, 's2': 10.595984806465973, 's3': 10.302980568076663, 's4': 10.009976329687353, 'r1': 11.720163547776519, 'r2': 12.013167786165829, 'r3': 12.428755037626447, 'r4': 12.844342289087065, 'VWAP.': 10.561193492500992, '14 period ADX.': 11.49069517283577, 0: 13.930904722320864}, page_content='2024-04-01'),
 Document(metadata={'20 period SMA': 11.524530601501464, '100 period SMA': 12.65177281856537, '200 period SMA': 9.111783488988877, '14 period RSI': 42.805810289313236, 'MACD': -0.3836601822514645, 'SIGNAL': -0.33352890203436913, 'BB_UPPER': 13.701869344372989, 'BB_MIDDLE': 11.524530601501464, 'BB_LOWER': 9.34719185862994, 'pivot': 11.269429000729339, 's1': 10.556855847336545, 's2': 10.011947015718013, 's3': 9.299373862325218, 's4': 8.586800708932424, 'r1': 11.81433783234787, 'r2': 12.526910985740665, 'r3': 13.071819817359197, 'r4': 13.616728648977729, 'VWAP.': 10.56183049578526, '14 period ADX.': 10.849998588267534, 0: 13.930904722320864}, page_content='2024-05-01'),
 Document(metadata={'20 period SMA': 11.343671941757203, '100 period SMA': 12.683534860610962, '200 period SMA': 9.135252937078477, '14 period RSI': 41.976501557885, 'MACD': -0.467870803725301, 'SIGNAL': -0.3603972823725555, 'BB_UPPER': 13.356275509092411, 'BB_MIDDLE': 11.343671941757203, 'BB_LOWER': 9.331068374421994, 'pivot': 10.631324665084465, 's1': 9.929764838503305, 's2': 9.560996237370379, 's3': 8.859436410789218, 's4': 8.157876584208058, 'r1': 11.000093266217391, 'r2': 11.701653092798551, 'r3': 12.070421693931477, 'r4': 12.439190295064403, 'VWAP.': 10.557726018859503, '14 period ADX.': 10.693051309834617, 0: 13.784170775986091}, page_content='2024-06-01'),
 Document(metadata={'20 period SMA': 11.29978175163269, '100 period SMA': 12.698820714950562, '200 period SMA': 9.161100636720658, '14 period RSI': 43.99730515211937, 'MACD': -0.4981885307812206, 'SIGNAL': -0.38795553205428857, 'BB_UPPER': 13.350942525592986, 'BB_MIDDLE': 11.29978175163269, 'BB_LOWER': 9.248620977672394, 'pivot': 10.117743609444567, 's1': 9.75146290843133, 's2': 9.424212399809436, 's3': 9.0579316987962, 's4': 8.691650997782963, 'r1': 10.444994118066461, 'r2': 10.811274819079697, 'r3': 11.138525327701592, 'r4': 11.465775836323486, 'VWAP.': 10.557663976430375, '14 period ADX.': 10.072492739606693, 0: 13.544550115476286}, page_content='2024-07-01'),
 Document(metadata={'20 period SMA': 11.40379776954651, '100 period SMA': 12.738915319442748, '200 period SMA': 9.2024634206295, '14 period RSI': 55.88236079221577, 'MACD': -0.2984336277177295, 'SIGNAL': -0.3700511511869768, 'BB_UPPER': 13.618724562982491, 'BB_MIDDLE': 11.40379776954651, 'BB_LOWER': 9.188870976110527, 'pivot': 10.548918319270056, 's1': 10.182592920095956, 's2': 9.90629683262355, 's3': 9.53997143344945, 's4': 9.17364603427535, 'r1': 10.825214406742463, 'r2': 11.191539805916562, 'r3': 11.467835893388969, 'r4': 11.744131980861376, 'VWAP.': 10.576968382885935, '14 period ADX.': 11.094599086266543, 0: 13.366781657136269}, page_content='2024-08-01'),
 Document(metadata={'20 period SMA': 11.494153547286988, '100 period SMA': 12.781056327819824, '200 period SMA': 9.243079746961593, '14 period RSI': 51.72285728981158, 'MACD': -0.2151776097751359, 'SIGNAL': -0.33907644290460864, 'BB_UPPER': 13.687709644844983, 'BB_MIDDLE': 11.494153547286988, 'BB_LOWER': 9.300597449728993, 'pivot': 12.343829543244405, 's1': 11.320877429352542, 's2': 9.45220159790186, 's3': 8.429249484009997, 's4': 7.406297370118134, 'r1': 14.212505374695088, 'r2': 15.23545748858695, 'r3': 17.104133320037633, 'r4': 18.972809151488313, 'VWAP.': 10.589784276957133, '14 period ADX.': 12.148045090790466, 0: 9.790493100822673}, page_content='2024-09-01'),
 Document(metadata={'20 period SMA': 11.588927125930786, '100 period SMA': 12.811844396591187, '200 period SMA': 9.2799820625782, '14 period RSI': 50.40945826048429, 'MACD': -0.1724098509175196, 'SIGNAL': -0.3057431245071909, 'BB_UPPER': 13.675667419704588, 'BB_MIDDLE': 11.588927125930786, 'BB_LOWER': 9.502186832156983, 'pivot': 12.58371182117564, 's1': 11.621482877983874, 's2': 11.01425081303562, 's3': 10.052021869843854, 's4': 9.089792926652088, 'r1': 13.190943886123895, 'r2': 14.153172829315661, 'r3': 14.760404894263916, 'r4': 15.36763695921217, 'VWAP.': 10.601739439897145, '14 period ADX.': 12.87495463936085, 0: 9.790493100822673}, page_content='2024-10-01'),
 Document(metadata={'20 period SMA': 11.606600189208985, '100 period SMA': 12.821263780593872, '200 period SMA': 9.312436600923538, '14 period RSI': 45.09087891864515, 'MACD': -0.244396489897591, 'SIGNAL': -0.2934737975852709, 'BB_UPPER': 13.649912655458856, 'BB_MIDDLE': 11.606600189208985, 'BB_LOWER': 9.563287722959114, 'pivot': 12.11283125315459, 's1': 11.542265188722684, 's2': 11.16812374597564, 's3': 10.597557681543734, 's4': 10.026991617111827, 'r1': 12.486972695901635, 'r2': 13.057538760333541, 'r3': 13.431680203080585, 'r4': 13.80582164582763, 'VWAP.': 10.60610032099565, '14 period ADX.': 12.290491347124204, 0: 9.940711007364461}, page_content='2024-11-01'),
 Document(metadata={'20 period SMA': 11.576338768005371, '100 period SMA': 12.82647123336792, '200 period SMA': 9.339461261034012, '14 period RSI': 43.4371089593742, 'MACD': -0.33401825357939785, 'SIGNAL': -0.30158268878409633, 'BB_UPPER': 13.691405988577891, 'BB_MIDDLE': 11.576338768005371, 'BB_LOWER': 9.461271547432851, 'pivot': 11.018821558754695, 's1': 9.910924819337385, 's2': 9.252517515872036, 's3': 8.144620776454726, 's4': 7.036724037037416, 'r1': 11.677228862220044, 'r2': 12.785125601637354, 'r3': 13.443532905102703, 'r4': 14.101940208568053, 'VWAP.': 10.603198674023805, '14 period ADX.': 11.428855887736452, 0: 13.545940764367407}, page_content='2024-12-01'),
 Document(metadata={'20 period SMA': 11.527421188354491, '100 period SMA': 12.837875938415527, '200 period SMA': 9.367433182001115, '14 period RSI': 45.24740921263234, 'MACD': -0.37028687085407874, 'SIGNAL': -0.3153235251980928, 'BB_UPPER': 13.696992124222902, 'BB_MIDDLE': 11.527421188354491, 'BB_LOWER': 9.357850252486081, 'pivot': 10.39055859902526, 's1': 9.636149503943699, 's2': 9.154341892714058, 's3': 8.399932797632497, 's4': 7.6455237025509355, 'r1': 10.872366210254901, 'r2': 11.626775305336462, 'r3': 12.108582916566103, 'r4': 12.590390527795744, 'VWAP.': 10.60003298775278, '14 period ADX.': 10.788503140414715, 0: 13.545940764367407}, page_content='2025-01-01'),
 Document(metadata={'20 period SMA': 11.40048565864563, '100 period SMA': 12.83448800086975, '200 period SMA': 9.397120584249496, '14 period RSI': 43.817693195652545, 'MACD': -0.42301647499669315, 'SIGNAL': -0.3368621151578129, 'BB_UPPER': 13.583928076043192, 'BB_MIDDLE': 11.40048565864563, 'BB_LOWER': 9.217043241248069, 'pivot': 10.305314149994446, 's1': 9.90529294406348, 's2': 9.314784916142093, 's3': 8.914763710211126, 's4': 8.514742504280159, 'r1': 10.895822177915832, 'r2': 11.2958433838468, 'r3': 11.886351411768185, 'r4': 12.476859439689571, 'VWAP.': 10.598320672725176, '14 period ADX.': 10.173197323817906, 0: 13.392695378675633}, page_content='2025-02-01'),
 Document(metadata={'20 period SMA': 11.304981994628907, '100 period SMA': 12.847476320266724, '200 period SMA': 9.432235049009323, '14 period RSI': 48.636737230005835, 'MACD': -0.3808348410028941, 'SIGNAL': -0.3456566603268292, 'BB_UPPER': 13.350227299936616, 'BB_MIDDLE': 11.304981994628907, 'BB_LOWER': 9.259736689321198, 'pivot': 10.42515996513796, 's1': 9.772771963650007, 's2': 9.407434720146695, 's3': 8.755046718658742, 's4': 8.102658717170788, 'r1': 10.790497208641272, 'r2': 11.442885210129225, 'r3': 11.808222453632537, 'r4': 12.173559697135849, 'VWAP.': 10.601406734446936, '14 period ADX.': 10.121587014483351, 0: 13.24557980841153}, page_content='2025-03-01'),
 Document(metadata={'20 period SMA': 11.285742807388306, '100 period SMA': 12.861666488647462, '200 period SMA': 9.469200550317764, '14 period RSI': 49.234258810850406, 'MACD': -0.3334220192284967, 'SIGNAL': -0.3432097321071627, 'BB_UPPER': 13.325156324915305, 'BB_MIDDLE': 11.285742807388306, 'BB_LOWER': 9.246329289861308, 'pivot': 10.99038562008072, 's1': 10.28796781001037, 's2': 9.451600331019272, 's3': 8.74918252094892, 's4': 8.04676471087857, 'r1': 11.82675309907182, 'r2': 12.52917090914217, 'r3': 13.365538388133269, 'r4': 14.201905867124367, 'VWAP.': 10.601551764849848, '14 period ADX.': 10.073663157896942, 0: 13.104348860957993}, page_content='2025-04-01')]

In [24]:
response = ChatAnaliseTecnica(
    query=f"Qual é a tendencia sobre a empresa {ticker}",
    dados=dados_indicadores,
    modelo_llm="deepseek-r1-distill-llama-70b",
    stream=True
)

In [25]:
for chunk in response:
    print(chunk, end="", flush=True)

<think>
Ok, vou analisar os dados técnicos fornecidos para entender a tendência da ação BBDC3. Primeiro, vou verificar as médias móveis. Vejo que as médias de 20, 100 e 200 períodos estão em níveis variáveis, mas a de 200 períodos está abaixo das demais, o que pode indicar uma tendência de baixa a longo prazo.

Em seguida, o RSI está em torno de 50, o que sugere que o ativo não está em território de sobrecompra ou sobrevenda. Isso pode indicar um mercado neutro ou de consolidação.

Olhando para o MACD, está negativo e abaixo da linha de sinal, o que pode indicar fraqueza na tendência de alta. A divergência entre o MACD e a linha de sinal pode sinalizar uma possível continuação da tendência de baixa.

As Bollinger Bands estão se contraindo, o que pode indicar baixa volatilidade e possibilidade de uma quebra de suporte ou resistência. O preço atual está perto do suporte, o que pode ser um ponto crítico.

O ADX está abaixo de 25, indicando uma tendência fraca, o que sugere que o mercado está em uma fase de indecisão ou consolidação.

Considerando todos esses fatores, parece que a tendência é neutra ou levemente bearish. Recomendo esperar por mais sinais claros antes de tomar uma decisão de compra ou venda.
</think>

### Análise Técnica da Ação BBDC3

#### **Trend Identification:**
- **Médias Móveis:**
  - **Média de 20 períodos:** 11.40379776954651
  - **Média de 100 períodos:** 12.738915319442748
  - **Média de 200 períodos:** 9.2024634206295
  - **Análise:** O preço atual está abaixo da média móvel de 20 períodos, indicando uma possível tendência de baixa no curto prazo. No entanto, a média de 200 períodos está abaixo das demais, o que pode indicar uma tendência de baixa a longo prazo.

- **ADX (14 períodos):** 12.148045090790466
  - **Análise:** O valor do ADX está abaixo de 25, o que indica uma tendência fraca no momento.

#### **Market Strength:**
- **RSI (14 períodos):** 51.72285728981158
  - **Análise:** O RSI está em um nível neutro, não indicando condições de sobrecompra ou sobrevenda.

- **MACD e Sinal:**
  - **MACD:** -0.2151776097751359
  - **Sinal:** -0.33907644290460864
  - **Análise:** O MACD está abaixo da linha de sinal, indicando uma tendência de baixa.

#### **Support and Resistance:**
- **Bollinger Bands:**
  - **Superior:** 13.618924562982491
  - **Médio:** 11.40379776954651
  - **Inferior:** 9.188870976110527
  - **Análise:** As bandas estão se contraindo, indicando baixa volatilidade no momento. O preço está perto da banda inferior, o que pode indicar um possível teste de suporte.

- **Níveis de Suporte e Resistência:**
  - **Pivot Point:** 12.343829543244405
  - **Suportes:** S1: 11.320877429352542, S2: 9.45220159790186, S3: 8.429249484009997, S4: 7.406297370118134
  - **Resistências:** R1: 14.212505374695088, R2: 15.23545748858695, R3: 17.104133320037633, R4: 18.972809151488313
  - **Análise:** O preço atual está perto do suporte S2, o que pode ser um ponto de testes de suporte.

#### **Possible Strategy:**
- **Tendência Atual:** A tendência parece ser neutra, com sinais de fraqueza na direção de alta.
- **Estratégia Recomendada:** Considerando os indicadores, é recomendável adotar uma estratégia de espera. O mercado está em uma fase de consolidação, e é melhor esperar por sinais mais claros antes de tomar uma decisão de compra ou venda.

### **Conclusão:**
- **Recomendação:** Aguardar mais sinais claros do mercado antes de realizar qualquer operação de compra ou venda. O mercado está em uma fase de baixa volatilidade e tendência fraca, o que não favorece operações de alto risco no momento.

In [26]:
ticker = 'BBDC3'
query = f"Qual é a tendencia sobre a empresa {ticker}"
tec = ModeloAnaliseTecnica(query=query,ticker=ticker)

In [27]:
response, dados_tecnicas = tec.chat_analise_tecnica()
for chunk in response: 
    print(chunk, end="", flush=True)

<think>
Okay, so I need to figure out the trend for BBDC3 using the provided technical indicators. Let me start by going through each indicator one by one.

First, looking at the Moving Averages. The 20-period SMA is around 11.5, the 100-period is about 12.65, and the 200-period is 9.33. The price is above the 200-period SMA but below the 20 and 100. That might suggest some mixed signals. The 20-period is below the 100-period, which usually indicates a downtrend, but since the price is above the 200, maybe it's trying to stabilize.

Next, the RSI is at 45. That's in the middle, so not overbought or oversold. It suggests the market is neutral right now. No strong buy or sell signals from RSI alone.

Now, the MACD is negative (-0.37) and the Signal line is also negative (-0.32). The MACD is below the Signal line, which is a bearish sign. It indicates that the downside momentum is stronger, so maybe a sell signal.

Looking at Bollinger Bands, the price is near the middle band. The bands are contracting, which means volatility is low. So, the market is not very active, and we might expect a breakout or breakdown soon.

The ADX is around 10.1, which is below 25. That means the trend is weak. Even though the MACD is bearish, the weak ADX suggests that the trend isn't very strong, so it might not be a clear downtrend.

Support and resistance levels: The current price is near the pivot point, which is 10.39. The next support is at 9.63, and resistance at 10.87. So, if the price breaks below the pivot, it might go down to 9.63. If it goes above 10.87, it might start an uptrend.

VWAP is around 10.6, which is close to the current price. It suggests that the price is averaging around that level, so maybe some support there.

Putting it all together: The moving averages are mixed, RSI is neutral, MACD is bearish but ADX is weak. Bollinger Bands are contracting, so maybe a breakout is coming. The price is near the pivot, so it's at a critical point.

So, the trend seems neutral to slightly bearish. The MACD suggests selling, but the weak ADX and contracting Bollinger Bands make me cautious. Maybe wait for a clearer signal or a breakout before making a move.

I think the best strategy is to wait for the price to either break above the resistance at 10.87 or below the support at 9.63. If it breaks above, maybe go long with a target at the next resistance. If it breaks below, short with a target at the next support. Until then, it's better to hold off.
</think>

**Análise Técnica da Ação BBDC3**

**Resumo da Análise:**

1. **Tendência Geral:**
   - **Médias Móveis:** A ação está acima da MMA de 200 períodos, indicando suporte de longo prazo. No entanto, a MMA de 20 períodos está abaixo da MMA de 100 períodos, sugerindo uma tendência de baixa no curto prazo.
   - **ADX (14 períodos):** O ADX está em 10.1, indicando uma tendência fraca, o que sugere que a direção do preço não é forte no momento.

2. **Força do Mercado:**
   - **RSI (14 períodos):** O RSI está em 45, indicando que o mercado está em território neutro, sem sinais de supercompra ou super-venda.
   - **MACD e Sinal:** O MACD está abaixo da linha de sinal, indicando um sinal de venda. No entanto, a diferença entre as duas linhas não é significativa, o que pode indicar uma fraqueza no momentum de baixa.

3. **Suporte e Resistência:**
   - **Bollinger Bands:** As bandas estão se contraindo, indicando baixa volatilidade. O preço está perto do meio das bandas, o que pode indicar um possível movimento de consolidação ou breakout.
   - **Níveis de Suporte e Resistência:** O preço está próximo do ponto pivô (10,39). O suporte imediato está em 9,63 e a resistência está em 10,87.

**Estratégia de Negociação Recomendada:**

- **Aguarde:** Devido à tendência fraca indicada pelo ADX e à volatilidade baixa das Bollinger Bands, é recomendável aguardar um movimento mais claro do preço.
- **Compra:** Se o preço ultrapassar a resistência de 10,87 com volume significativo, pode ser um sinal de entrada para uma tendência de alta. O alvo seria o próximo nível de resistência em 11,42.
- **Venda:** Se o preço romper o suporte de 9,63 com volume, pode ser um sinal de entrada para uma tendência de baixa. O alvo seria o próximo nível de suporte em 9,15.
- **Monitoramento:** Mantenha-se atento aos níveis de suporte e resistência, bem como às bandas de Bollinger, pois um breakout pode indicar o início de uma nova tendência.

**Conclusão:**
A ação BBDC3 está em uma fase de consolidação, com sinais mistos das médias móveis e do MACD. A baixa volatilidade e o ADX fraco sugerem que o mercado está indeciso. A melhor estratégia no momento é aguardar um movimento mais definido do preço antes de tomar uma decisão de compra ou venda.

In [28]:
retransfromando_pandas(dados_tecnicas)

,20 period SMA,100 period SMA,200 period SMA,14 period RSI,MACD,SIGNAL,BB_UPPER,BB_MIDDLE,BB_LOWER,pivot,...,s3,s4,r1,r2,r3,r4,VWAP.,14 period ADX.,0,data
0,11.826823,12.346338,8.903816,52.005253,-0.365994,-0.482987,14.122698,11.826823,9.530948,10.985269,...,9.981002,9.593391,11.214312,11.601923,11.830967,12.060010,10.498135,12.943188,10.040222,2023-11-01
1,11.899755,12.409824,8.950631,55.471365,-0.198712,-0.426132,14.313700,11.899755,9.485810,12.097314,...,9.277352,8.503994,13.370560,14.143918,15.417164,16.690410,10.519192,13.574611,10.171576,2023-12-01
2,11.828928,12.465098,8.988539,50.040245,-0.165671,-0.374040,14.104911,11.828928,9.552945,13.300760,...,11.213037,10.582892,14.128193,14.758338,15.585770,16.413203,10.533344,13.808201,10.397135,2024-01-01
3,11.797445,12.508615,9.020360,45.387456,-0.235398,-0.346312,14.101198,11.797445,9.493693,12.694266,...,10.212681,9.234364,13.219216,14.197533,14.722484,15.247434,10.547981,12.915247,10.609161,2024-02-01
4,11.775382,12.554518,9.053513,47.155997,-0.254757,-0.328001,14.084718,11.775382,9.466046,11.642744,...,7.957915,6.521608,12.454959,13.891265,14.703481,15.515696,10.555957,12.086075,10.808466,2024-03-01
5,11.680087,12.606847,9.085401,45.881453,-0.292978,-0.320996,13.931892,11.680087,9.428281,11.304576,...,10.302981,10.009976,11.720164,12.013168,12.428755,12.844342,10.561193,11.490695,13.930905,2024-04-01
6,11.524531,12.651773,9.111783,42.805810,-0.383660,-0.333529,13.701869,11.524531,9.347192,11.269429,...,9.299374,8.586801,11.814338,12.526911,13.071820,13.616729,10.561830,10.849999,13.930905,2024-05-01
7,11.343672,12.683535,9.135253,41.976502,-0.467871,-0.360397,13.356276,11.343672,9.331068,10.631325,...,8.859436,8.157877,11.000093,11.701653,12.070422,12.439190,10.557726,10.693051,13.784171,2024-06-01
8,11.299782,12.698821,9.161101,43.997305,-0.498189,-0.387956,13.350943,11.299782,9.248621,10.117744,...,9.057932,8.691651,10.444994,10.811275,11.138525,11.465776,10.557664,10.072493,13.544550,2024-07-01
9,11.403798,12.738915,9.202463,55.882361,-0.298434,-0.370051,13.618725,11.403798,9.188871,10.548918,...,9.539971,9.173646,10.825214,11.191540,11.467836,11.744132,10.576968,11.094599,13.366782,2024-08-01
10,11.494154,12.781056,9.243080,51.722857,-0.215178,-0.339076,13.687710,11.494154,9.300597,12.343830,...,8.429249,7.406297,14.212505,15.235457,17.104133,18.972809,10.589784,12.148045,9.790493,2024-09-01
11,11.588927,12.811844,9.279982,50.409458,-0.172410,-0.305743,13.675667,11.588927,9.502187,12.583712,...,10.052022,9.089793,13.190944,14.153173,14.760405,15.367637,10.601739,12.874955,9.790493,2024-10-01
12,11.606600,12.821264,9.312437,45.090879,-0.244396,-0.293474,13.649913,11.606600,9.563288,12.112831,...,10.597558,10.026992,12.486973,13.057539,13.431680,13.805822,10.606100,12.290491,9.940711,2024-11-01
13,11.576339,12.826471,9.339461,43.437109,-0.334018,-0.301583,13.691406,11.576339,9.461272,11.018822,...,8.144621,7.036724,11.677229,12.785126,13.443533,14.101940,10.603199,11.428856,13.545941,2024-12-01
14,11.527421,12.837876,9.367433,45.247409,-0.370287,-0.315324,13.696992,11.527421,9.357850,10.390559,...,8.399933,7.645524,10.872366,11.626775,12.108583,12.590391,10.600033,10.788503,13.545941,2025-01-01
15,11.400486,12.834488,9.397121,43.817693,-0.423016,-0.336862,13.583928,11.400486,9.217043,10.305314,...,8.914764,8.514743,10.895822,11.295843,11.886351,12.476859,10.598321,10.173197,13.392695,2025-02-01
16,11.304982,12.847476,9.432235,48.636737,-0.380835,-0.345657,13.350227,11.304982,9.259737,10.425160,...,8.755047,8.102659,10.790497,11.442885,11.808222,12.173560,10.601407,10.121587,13.245580,2025-03-01
17,11.285743,12.861666,9.469201,49.234259,-0.333422,-0.343210,13.325156,11.285743,9.246329,10.990386,...,8.749183,8.046765,11.826753,12.529171,13.365538,14.201906,10.601552,10.073663,13.104349,2025-04-01

In [29]:
acao = yf.Ticker('WIZC3.SA')
info = acao.info

In [30]:
acao.history(period="10Y", interval="1d")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2015-06-05 00:00:00-03:00,7.038382,7.323022,6.986629,7.193640,15536400,0.0,0.0
2015-06-08 00:00:00-03:00,7.302321,7.338548,7.064258,7.131536,1648300,0.0,0.0
2015-06-09 00:00:00-03:00,7.131536,7.162588,6.996979,7.064257,2161400,0.0,0.0
2015-06-10 00:00:00-03:00,7.090132,7.281618,7.069431,7.245391,676000,0.0,0.0
2015-06-11 00:00:00-03:00,7.250568,7.504156,7.167763,7.379950,1118600,0.0,0.0
...,...,...,...,...,...,...,...
2025-03-26 00:00:00-03:00,6.250000,6.320000,6.210000,6.210000,357600,0.0,0.0
2025-03-27 00:00:00-03:00,6.320000,6.320000,5.970000,5.970000,988200,0.0,0.0
2025-03-28 00:00:00-03:00,6.000000,6.070000,5.960000,5.980000,443800,0.0,0.0
2025-03-31 00:00:00-03:00,5.980000,6.070000,5.900000,6.020000,377800,0.0,0.0
2025-04-01 00:00:00-03:00,6.060000,6.060000,5.990000,6.020000,182900,0.0,0.0

# Valuation

In [31]:
ticker = 'WHRL3'
query = f"Qual é o valuation da empresa {ticker}"
chat_valu = ModeloValuation(query=f"Qual é o valuation da empresa {ticker}", ticker=ticker, anos_projecao=5, taxa_crescimento_perpetuidade=0.014, calculo_necessidade_capital_de_giro=False, stream=True)

response= chat_valu.chat_valuation()

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

Diferença entre valuation e cotação: 57.47%

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [32]:
for chunk in response: 
    print(chunk, end="", flush=True)

<think>
Ok, eu preciso avaliar se a empresa WHRL3 está supervalorizada ou subvalorizada. Vou começar analisando os dados fornecidos.

Primeiro, vejo os preços dos valuations e o preço atual. O preço pelo método Gordon Growth Model é de R$ 6,22, enquanto o preço pelo DCF é de R$ -0,98. O preço atual é de R$ 3,95. Isso já me chama a atenção porque o DCF deu um valor negativo, o que é incomum e pode indicar problemas na modelagem ou nas entradas de dados.

Vou verificar os inputs usados no DCF. A margem EBIT é de 7,64%, o que parece razoável. A última receita foi de R$ 12.9317 bilhões, um número significativo. No entanto, a variação da receita está marcada como NaN, o que pode ser um problema. O ratio de depreciação/CAPEX é de 0,8815, e o CAPEX/receita é de 0,0205, indicando investimentos moderados. O WACC é de 30,5%, o que é bastante alto e pode afetar o valor presente dos fluxos de caixa.

A quantidade de ações é de 1.50279 bilhões, com dívida total de R$ 1.30767 bilhões. O caixa disponível é de R$ 2.86533 bilhões, outros ativos de R$ 744.309 milhões, passivos menos dívida de R$ 6.56594 bilhões, necessidade de capital de giro de R$ 377.66 milhões e percentual de imposto de 16,36%. Esses números indicam uma empresa com alta dívida, mas também com um bom nível de caixa.

Agora, olhando para o valuation do fluxo de caixa, vejo que a receita anual está crescendo consistentemente, assim como o EBIT. O imposto também está aumentando, o que é esperado. O CAPEX está subindo gradualmente, e a depreciação acompanha esse aumento. O fluxo de caixa ajustado é positivo e crescente, mas o valor presente desses fluxos de caixa está diminuindo a cada ano, o que é preocupante. Isso pode indicar que os fluxos de caixa futuros estão sendo descontados a uma taxa alta, ou que as projeções estão muito otimistas.

No valuation pelo método Gordon Growth Model, o dividendo médiano é de R$ 0,423, com uma taxa de juros livre de risco de 14,86%, beta de 0,577, CAPM de 11,36%, taxa de crescimento sustentável de 4,56%. O valuation resultante é de R$ 6,22 por ação, com uma diferença de R$ 57,47 em relação ao preço atual de R$ 3,95.

Comparando os dois métodos, o DCF deu um valor negativo, o que é anormal, enquanto o Gordon deu um valor significativamente maior que o preço atual. Isso sugere uma grande discrepância entre os métodos, possivelmente devido a problemas no DCF, como inputs inconsistentes ou taxas de desconto muito altas.

Analisei a lucratividade e sustentabilidade financeira. O fluxo de caixa projetado é positivo, mas o CAPEX está aumentando, o que pode afetar os fluxos futuros. A dívida é alta, mas o caixa disponível é significativo, o que pode mitigar riscos. O WACC de 30,5% parece alto e pode estar inflacionando o desconto dos fluxos de caixa, contribuindo para o baixo valuation no DCF.

Os riscos incluem a sustentabilidade das taxas de crescimento de receita e EBIT, que parecem altas e podem não se manter. O nível de dívida é preocupante, e o WACC pode não refletir adequadamente o custo de capital. Além disso, o DCF apresentou um valor negativo, o que é incomum e pode indicar erros na modelagem.

Concluindo, o preço pelo Gordon é significativamente maior que o preço atual, sugerindo que a empresa está subvalorizada. No entanto, o DCF negativo é um sinal de alerta. Recomendo que os investidores analisem mais a fundo os fundamentos da empresa e as metodologias de valuation utilizadas antes de tomar decisões.
</think>

### Análise de Valuation da Empresa WHRL3

#### 1. Comparação entre os Métodos de Valuation

- **Preços dos Valuation e Atual:**
  - **Método Gordon Growth Model (Preço Gordon):** R$ 6,22
  - **Método Discounted Cash Flow (DCF):** R$ -0,98
  - **Preço Atual:** R$ 3,95

- **Observações:**
  - O valor obtido pelo método DCF é negativo, o que é incomum e pode indicar problemas na modelagem ou nos dados de entrada.
  - O preço pelo método Gordon é significativamente maior que o preço atual, sugerindo uma possível subvalorização da ação.

- **Fatores que Influenciam a Discrepância:**
  - **Projeções de Fluxo de Caixa:** O DCF depende fortemente das projeções de fluxo de caixa futuras. Se as projeções forem pessimistas ou se os custos de capital (WACC) forem muito altos, o valor presente pode ser negativo.
  - **Taxa de Crescimento Sustentável (g):** No método Gordon, uma taxa de crescimento mais otimista pode resultar em um valor mais alto.
  - **WACC Elevado:** O WACC de 30,5% é relativamente alto, o que pode estar reduzindo significativamente o valor presente dos fluxos de caixa no DCF.

#### 2. Análise de Lucratividade e Sustentabilidade Financeira

- **Fluxo de Caixa Projetado:**
  - O fluxo de caixa ajustado é positivo em todos os anos projetados, indicando que a empresa está gerando caixa operacional.
  - No entanto, o valor presente do fluxo de caixa diminui ao longo dos anos, o que pode indicar que os fluxos de caixa futuros estão sendo descontados a uma taxa muito alta ou que as projeções de crescimento são conservadoras.

- **CAPEX e Depreciação:**
  - O CAPEX está aumentando gradualmente, o que é comum em empresas em crescimento.
  - A depreciação também está aumentando, mas em uma proporção menor que o CAPEX, indicando que a empresa está investindo em ativos que depreciarão ao longo do tempo.

- **Sustentabilidade do Valor da Empresa:**
  - O valor da empresa, conforme calculado pelo método Gordon, justifica o preço atual, considerando a taxa de crescimento sustentável de 4,56%.
  - No entanto, o valor negativo do DCF sugere que as expectativas de crescimento futuras podem estar sendo descontadas de forma excessiva.

#### 3. Riscos e Inconsistências

- **Crescimento de Receita e EBIT:**
  - A receita e o EBIT estão projetados para crescer consistentemente nos próximos anos, mas as taxas de crescimento podem ser consideradas altas, o que pode indicar uma possível sobrevalorização no método Gordon.

- **Nível de Dívida:**
  - A dívida total é significativa (R$ 1.30767 bilhões), mas a empresa também tem um montante relevante de caixa disponível (R$ 2.86533 bilhões), o que pode ajudar a mitigar os riscos associados à dívida.
  - A relação dívida/caixa é de aproximadamente 0,45, o que não é excessivamente preocupante, mas merece atenção.

- **WACC:**
  - O WACC de 30,5% é relativamente alto e pode estar superestimando o custo de capital, o que afeta diretamente o valor presente dos fluxos de caixa no DCF.

#### 4. Conclusão e Recomendação

- **Conclusão:**
  - O preço calculado pelo método Gordon Growth Model (R$ 6,22) é significativamente maior que o preço atual (R$ 3,95), sugerindo que a empresa está subvalorizada.
  - No entanto, o valor negativo do DCF (R$ -0,98) é um sinal de alerta e pode indicar problemas na modelagem ou nas expectativas de crescimento futuras.

- **Recomendação:**
  - **Investidores:** Devem analisar mais a fundo os fundamentos da empresa, especialmente as projeções de crescimento e os custos de capital utilizados no DCF.
  - **Análise Adicional:** Recomenda-se verificar se as taxas de crescimento projetadas são realistas e se o WACC está adequadamente calculado.
  - **Ação:** Considerando o preço atual e o valuation pelo método Gordon, pode ser uma boa oportunidade de investimento, mas com cautela devido à discrepância nos métodos de valuation.

### Resposta Final

A empresa WHRL3 apresenta um valuation de R$ 6,22 pelo método Gordon Growth Model e R$ -0,98 pelo método DCF. Considerando a discrepância e os fatores analisados, a empresa parece estar subvalorizada, mas é recomendável uma análise mais aprofundada das projeções e custos de capital antes de tomar decisões de investimento.

# Chat retirando ticker

In [33]:
import json
with open('dados/empresas.json', 'r') as f:
    dados_empresa = json.load(f)

In [34]:
from langchain_groq import ChatGroq
from langchain_core.output_parsers import StrOutputParser
from dotenv import load_dotenv
from chat_bots import get_secret_key
from pydantic import SecretStr
from langchain_core.prompts import PromptTemplate
from typing import Dict

load_dotenv()

try:
    api_secret_groq = get_secret_key("GROQ_API_KEY")
except KeyError as exc:
    raise ValueError("API key inválida ou não definida") from exc

load_dotenv()


def ChatPegaTicker(
    query: str,
    dados_empresas:Dict[str,str],
    api_secret: SecretStr | None = api_secret_groq,
    modelo_llm: str = "llama-3.2-3b-preview",
) -> str:
    model = ChatGroq(
        api_key=api_secret,
        model=modelo_llm,
        temperature=0.5,
        stop_sequences=None,
    )

    prompt = PromptTemplate(
        input_variables=["query", "dados_empresas"],
        template="""
        
                Você recebe a seguinte consulta: "{query}"
                
                Sua única missão é identificar o ticker da empresa mencionada, caso exista.

                Extraia o nome da empresa na consulta.
                Encontre seu código de negociação na bolsa de valores.
                Responda apenas com o ticker, sem qualquer outra informação adicional.
                Exemplo:
                Entrada: "O que você pode me dizer sobre o banco Bradesco?"
                Saída: BBDC4
                
                Voce recebe os nomes e o codigo na empresa no arquivo {dados_empresas}
                
                Utlize esse arquivo para identificar qual e o codigo da acao
                
            De como resposta apenas o codigo da acao, sem nenhum comentario.

            Se não encontrar um ticker válido, responda que nao encontrou.

      """,
    )

    llm_chain = prompt | model | StrOutputParser()

    resposta = llm_chain.invoke({'query':query, 'dados_empresas':dados_empresas})

    return resposta

In [35]:
query = "O que vc pode me dizer da petrobras"
response = ChatPegaTicker(query=query, dados_empresas=dados_empresa)
response

'PETR3'

In [36]:
from juncao_modelos_dados import ModeloFundamentos, ModeloValuation, ModeloSentimento, ModeloAnaliseTecnica

# Pegando icone da empresa

In [37]:
from selenium.webdriver.common.by import By
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys

class PegandoLogotipo:
    def __init__(self, ticker: str) -> None:
        self.ticker = ticker
        
    def options(self) -> webdriver.ChromeOptions:
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument("--no-sandbox")
        chrome_options.add_argument("--disable-dev-shm-usage")
        chrome_options.add_argument("--disable-gpu")
        chrome_options.add_argument("--disable-features=NetworkService")
        chrome_options.add_argument("--window-size=1920x1080")
        chrome_options.add_argument("--disable-features=VizDisplayCompositor")
        return chrome_options

    def driver(self) -> webdriver.Chrome:
        driver = webdriver.Chrome(options=self.options())
        return driver

    def pegar_logotipo(self) -> str | None:
        driver = self.driver()
        driver.get(f"https://br.tradingview.com/symbols/BMFBOVESPA-{self.ticker}/")
        image_element = WebDriverWait(driver, 10).until(
                EC.presence_of_element_located((By.XPATH, "/html/body/div[3]/div[4]/div[2]/div[1]/div[1]/div/div/div/div[1]/img[3]"))
            )
            
            # Extrai o link da imagem (atributo 'src')
        image_link = image_element.get_attribute("src")
        return image_link

In [38]:
ticker = 'PETR3'
pegar_logotipo = PegandoLogotipo(ticker=ticker)
pegar_logotipo.pegar_logotipo()

'https://s3-symbol-logo.tradingview.com/brasileiro-petrobras--big.svg'

# f

In [39]:
import yfinance as yf
ticker = 'VALE3.SA'
acao = yf.Ticker(ticker)
info = acao.info
response = ChatTradutor(info['longBusinessSummary'])
response.split('\n\n')[-1]

'Tradução para português:\nA Vale S.A. é uma empresa que produz e vende minério de ferro, pellets de minério de ferro, níquel e cobre no Brasil e internacionalmente. A empresa opera em dois segmentos: Iron Solutions e Energy Transition Materials. O segmento Iron Solutions produz e extrai minério de ferro e pellets, além de outros produtos ferrosos e fornece serviços logísticos relacionados. O segmento Energy Transition Materials produz e extrai níquel e seus subprodutos, como ouro, prata, cobalto e metais preciosos, além de cobre usado na construção civil para produzir tubulações e fios elétricos.'

In [40]:
from bs4 import BeautifulSoup as Soup
from langchain_community.document_loaders.recursive_url_loader import RecursiveUrlLoader

In [41]:
from tratando_dados import TratarDadosNoticias
from coleta_dados import LinksExtractorBS4
from selenium import webdriver
import os
from pydantic import SecretStr

In [42]:
api_secret_groq = os.getenv("GROQ_API_KEY")
api_secret_serper = os.getenv("API_KEY_SERPER")

In [43]:
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--disable-features=NetworkService")
chrome_options.add_argument("--window-size=1920x1080")
chrome_options.add_argument("--disable-features=VizDisplayCompositor")

In [44]:
tratando_dados = TratarDadosNoticias(acao='PETR3', options=chrome_options, api_secret_groq=SecretStr(api_secret_groq), api_secret_serper=SecretStr(api_secret_serper))

noticias = tratando_dados.clean_chat_html_bs4()

In [45]:
noticias.split('\nNew notice\n')

['',
 'o mercado financeiro\nPetrobras (PETR3; PETR4): ajuste no diesel é positivo para os negócios? Itaú BBA avalia\nA estatal anunciou uma redução de 4,6% no preço do diesel praticado nas refinarias\nO Itaú BBA considerou que a magnitude do ajuste de preços da Petrobras (PETR3; PETR4) para o diesel colocará os valores domésticos do combustível de volta ao limite superior das faixas de preço de referência. O BBA aponta que as decisões mantêm o posicionamento anterior da empresa em relação aos preços do diesel.\nAs melhores ações para investir em abril, segundo 7 bancos e corretoras\nDe olho na demanda global, maior gestora do mundo anuncia mudança de rota\nAs razões por trás do investimento de R$ 20 milhões de Rafael Ferri na Casas Bahia\nA presidente d',
 ' nos EUA operam mistos diante da incerteza sobre tarifas do governo Trump\nIbovespa hojeIbovespa sobe aos 131,5 mil pontos; dólar comercial recua a R$ 5,68 e juros futuros caem por toda a curva.Ações da Vale (VALE3), da Petrobras (PETR4), de varejistas e de grandes bancos sobem.Galípolo: economia do Brasil tem série de subsídios cruzados, perversos e regressivos.Senado aprova Projeto de Lei da Reciprocidade para sanções comerciais.Confira as últimas dos mercados\nEmbraer (EMBR3) vira para alta, com mais 0,23%, a R$ 65,90\nNova máxima! Ibovespa agora sobe 1,32%, aos 131.982,29 pontos\nÍndice de Small Caps (SMLL) faz nova máxima, com alta de 1,91%, aos 1.957,08 pontos\nIbovespa renova máxima do dia, com mais 1,31%, aos 131.967,09 pontos\nÍndice de ',
 'inanceiro\nPetrobras (PETR3; PETR4) anuncia redução no preço do diesel; veja novo valor\nO ajuste no preço do diesel vem 59 dias após uma alta de 6,29% (R$ 0,22 por litro) no fim de janeiro\nA presidente da Petrobras (PETR3; PETR4), Magda Chambriard, anunciou nesta segunda-feira (31) uma redução de 4,6% no preço do diesel praticado nas refinarias da estatal. Segundo Chambriard, isso equivale a uma redução de R$ 0,17 por litro de diesel A.\nAs razões por trás do investimento de R$ 20 milhões de Rafael Ferri na Casas Bahia\nO que se sabe até agora sobre a operação de compra do Banco Master pelo BRB\nMercado Livre: o que a favorita dos analistas tem que supera as varejistas brasileiras\nA presidente da Petrobras indicou, ainda, que o preço do QAV tam',
 'rcado financeiro\nPetrobras (PETR3;PETR4) abre o jogo sobre participação na Braskem e BRKM5 salta 10%\nEstatal se pronunciou sobre notícia de que estaria negociado um novo acordo com credores da Novonor\nA Petrobras (PETR3;PETR4) se pronunciou nesta quarta-feira (26), em comunicado enviado à Comissão de Valores Mobiliários (CVM), sobre a notícia publicada pelo jornal Valor Econômico de que a empresa estaria negociado um novo acordo com bancos credores da Novonor, que detém ações na Braskem (BRKM5).\nAcionista da Petrobras (PETR3; PETR4) faz nova indicação para o Conselho fiscal\nBTG mantém visão positiva para Petrobras (PETR4), apesar de investimentos arriscarem dividendos\nPetrobras (PETR3; PETR4): Citi prevê dividendos extras de até R$ 3 bilhõe',
 ' do mês - InfoMoney\nFluxo e minério de ferro: o que faz o Ibovespa subir forte no 1º pregão do mês\nAlguns investidores têm alocado recursos em mercados emergentes, como o Brasil, aproveitando oportunidades\nA valorização de 1,86% do minério de ferro estimula o Ibovespa nesta manhã de terça-feira, 1º de abril, que mira o nível dos 131 mil pontos, um dia antes da efetivação do plano de tarifas do presidente dos Estados Unidos, Donald Trump. A alta aqui destoa da queda das bolsas em Nova York, em meio a incertezas relacionadas às medidas. Neste cenário, alguns investidores têm alocado recursos em mercados emergentes, como o Brasil, aproveitando oportunidades, cita Henrique Lenzi, operador de renda variável da Manchester Investimentos.“Há uma gr',
 'acora - InfoMoney\nPetrobras lança concorrência de plataforma para revitalizar campo de Albacora\nA abertura das propostas está prevista para 1º de outubro, conforme a publicação\nRIO DE JANEIRO (Reuters) – A Petrobras (PETR3;PETR4) lançou nesta segunda-feira licitação para a contratação de plataforma do tipo FPSO para o projeto de revitalização do campo de Albacora, na Bacia de Campos, no norte fluminense, segundo publicação no Diário Oficial da União (DOU).A abertura das propostas está prevista para 1º de outubro, conforme a publicação.Chamada de P-88, a plataforma tem previsão para entrar em operação após 2030, de acordo com o plano estratégico da Petrobras 2025-2029, com capacidade para produzir 120 mil barris de petróleo ao dia.\nLeia tamb',
 'ias do mercado financeiro\nDia da Libertação: mercado global opera em alerta antes de tarifas de Trump; Ibovespa avança\nPresidente americano deve anunciar tarifas recíprocas a outros países na quarta-feira (2); veja impactos no dólar, no ouro e nos mercados pelo mundo\nTrump planeja anunciar nesta quarta-feira (2) tarifas recíprocas que corresponderiam às taxas cobradas por outros países e levariam em conta outros subsídios. (Imagem: zignalstudio em Adobe Stock)\nO Ibovespa hoje opera em alta, na véspera do que tem sido chamado de “Dia da Libertação”, data em que o presidente dos Estados Unidos, Donald Trump, deve anunciar tarifas recíprocas como uma forma de retaliação à taxação de outros países sobre produtos americanos. No início da tarde d',
 'is notícias do mercado financeiro\nMercado financeiro hoje: tarifas de Trump contra “todos os países” e IPCA-15 definem o rumo do Ibovespa\nVolatilidade exterior pode pesar sobre a Bolsa brasileira nesta quinta-feira em meio à falta de direção nas commodities\nPor Luciana Xavier, Silvana Rocha e Camilly Rosaboni\nOs temas que impactam o mercado financeiro hoje. (Foto: Adobe Stock)\nA agenda econômica desta quinta-feira (27) traz o Índice Nacional de Preços ao Consumidor Amplo 15 (IPCA-15) de março, o resultado do Governo Central em fevereiro e, nos EUA, a leitura final do Produto Interno Bruto (PIB) do quarto trimestre de 2024. O mercado financeiro hoje ainda permanece atento às tarifas comerciais impostas pelos Estados Unidos.\nNem todo dividend',
 'o financeiro\nAcionista da Petrobras (PETR3; PETR4) faz nova indicação para o Conselho fiscal\nA eleição ocorrerá durante a Assembleia Geral Ordinária (AGO) da companhia em 16 de abril\nA Petrobras (PETR3; PETR4) informou que recebeu de fundos de investimentos geridos pela Franklin Resources a solicitação de substituição do membro suplente do Conselho fiscal para a eleição em separado dos detentores de ações preferenciais, que ocorrerá durante a Assembleia Geral Ordinária (AGO) da companhia, no 16 de abril.\nA ação da “sócia da Petrobras” que pode subir 50% e está no radar do BTG Pactual\nFortune: O mistério do US$ 1,4 bilhão que não aparece na contabilidade da Tesla\nEmpréstimo consignado CLT: veja como conseguir o menor juro do mercado\nA gestor',
 'ces dos EUA fecham mistos antes de tarifas de Trump entrarem em vigor, dia 2\nAdeus, março! O ano está voando e chegamos ao quarto mês de 2025. Neste último dia de março, institucionalmente, o país relembra os 61 anos do golpe militar de 1964, mas o mundo dos negócios olha mesmo é para Washington, onde o presidente dos EUA, Donald Trump, acena com suas tarifas globais que entram em vigor dia 2 de abril, depois de amanhã.O resultado é cautela, temor e preocupação, de modo que o Ibovespa acabou descendo 1,25%, aos 130.259,54 pontos, uma baixa de 1.642,64 pontos. Apesar do resultado deste último dia, o mês se encerrou com alta acumulada de 6,08%, o melhor mês desde agosto do ano passado, quando terminou com mais 6,54%.Tarifas dominam marçoNesse']

In [46]:
text_bs4 = LinksExtractorBS4()
text = text_bs4.clean_text_bs4(url='https://br.advfn.com/noticias/PAPERBR/2025/artigo/95596556')

Error fetching URL: Redirect response '302 Found' for url 'https://br.advfn.com/noticias/PAPERBR/2025/artigo/95596556'
Redirect location: '/jornal/2025/03/petrobras-celebra-acordo-de-us-283-milhoes-para-encerrar-litigio-com-a-eig-energy-nos-eua'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302

In [47]:
def test_dados_fundamentalistas_completo():
    df = DadosFundamentalistas("PETR4").dados_fundamentalistas_completo()
    assert isinstance(df, pd.DataFrame)
    assert not df.empty

In [48]:
df = DadosFundamentalistas("PETR4")

In [49]:
df.dados_fundamentalistas_completo()

,receita_liquida,resultado_bruto,ebit,amortizacao,ebitda,lucro_liquido,lucro_por_acao,datas,tic,capex_tres_meses,...,retorno_sobre_patrimonio_liquido_inicial,retorno_sobre_ativo_inicial,margem_bruta,margem_liquida,margem_ebit,margem_ebitda,giro_do_ativo_inicial,alavancagem_financeira,passivo_patrimonio_liquido,divida_liquida_ebitda
0,129580.0,66580.0,46460.0,-16540.0,63000.0,32560.0,2.50,2024-09-30,PETR4,-24640.0,...,0.219,0.083,0.518,0.168,0.325,0.478,0.49,2.74,1.74,1.14
1,122260.0,61050.0,33540.0,-16360.0,49900.0,-2610.0,- 0.20,2024-06-30,PETR4,-15260.0,...,0.212,0.080,0.522,0.158,0.330,0.486,0.50,2.83,1.83,1.19
2,117720.0,60700.0,44030.0,-16650.0,60680.0,23700.0,1.82,2024-03-31,PETR4,-14050.0,...,0.274,0.113,0.525,0.224,0.353,0.511,0.50,2.62,1.62,1.00
3,134260.0,72630.0,39630.0,-20490.0,60120.0,31040.0,2.38,2023-12-31,PETR4,-17790.0,...,0.344,0.128,0.527,0.243,0.370,0.518,0.52,2.76,1.76,0.91
4,124830.0,66320.0,47550.0,-19480.0,67030.0,26630.0,2.04,2023-09-30,PETR4,-15540.0,...,0.368,0.144,0.511,0.255,0.387,0.527,0.57,2.66,1.66,0.87
5,113840.0,57680.0,41970.0,-18280.0,60250.0,28780.0,2.21,2023-06-30,PETR4,-14390.0,...,0.381,0.156,0.506,0.269,0.403,0.531,0.58,2.67,1.67,0.74
6,139070.0,73310.0,60200.0,-17770.0,77970.0,38160.0,2.93,2023-03-31,PETR4,-12590.0,...,0.419,0.182,0.521,0.285,0.453,0.569,0.64,2.43,1.43,0.60
7,158580.0,76640.0,57810.0,-19460.0,77270.0,43340.0,3.32,2022-12-31,PETR4,-18710.0,...,0.486,0.194,0.521,0.294,0.459,0.576,0.66,2.69,1.69,0.65
8,170080.0,86840.0,74610.0,-18540.0,93150.0,46100.0,3.53,2022-09-30,PETR4,-10230.0,...,0.478,0.181,0.513,0.286,0.478,0.598,0.63,2.54,1.54,0.73
9,170960.0,95860.0,96430.0,-18620.0,115050.0,54330.0,4.16,2022-06-30,PETR4,-8380.0,...,0.454,0.172,0.509,0.284,0.504,0.634,0.60,2.45,1.45,0.54
10,141640.0,74770.0,65400.0,-18500.0,83900.0,44560.0,3.42,2022-03-31,PETR4,-12340.0,...,0.479,0.150,0.493,0.295,0.477,0.618,0.51,2.30,1.30,0.62
11,134190.0,59050.0,58290.0,-18720.0,77010.0,31500.0,2.42,2021-12-31,PETR4,-9410.0,...,0.346,0.108,0.485,0.236,0.466,0.620,0.46,2.51,1.51,0.96
12,121590.0,59550.0,66460.0,-17770.0,84230.0,31140.0,2.39,2021-09-30,PETR4,-7860.0,...,0.545,0.140,0.511,0.343,0.561,0.724,0.41,2.64,1.64,0.93
13,110710.0,57010.0,52180.0,-16470.0,68660.0,42860.0,3.29,2021-06-30,PETR4,-7890.0,...,0.422,0.101,0.511,0.299,0.502,0.688,0.34,2.64,1.64,1.14
14,86170.0,44030.0,33900.0,-16810.0,50710.0,1170.0,0.09,2021-03-31,PETR4,-8980.0,...,0.245,0.058,0.482,0.201,0.456,0.679,0.29,3.19,2.19,1.75
15,74970.0,40360.0,68010.0,-13330.0,81340.0,59890.0,4.59,2020-12-31,PETR4,-7460.0,...,0.024,0.008,0.456,0.026,0.182,0.415,0.29,3.20,2.20,2.94
16,70730.0,33770.0,18030.0,-17000.0,35030.0,-1550.0,- 0.12,2020-09-30,PETR4,-5960.0,...,-0.146,-0.048,0.433,-0.160,-0.015,0.221,0.30,3.90,2.90,6.12
17,50900.0,18220.0,9020.0,-15960.0,24980.0,-2710.0,- 0.21,2020-06-30,PETR4,-8220.0,...,-0.112,-0.035,0.410,-0.119,-0.028,0.200,0.30,4.18,3.18,6.89
18,75470.0,31620.0,-45440.0,-17070.0,-28370.0,-48520.0,- 3.72,2020-03-31,PETR4,-8340.0,...,-0.044,-0.013,0.420,-0.040,0.072,0.284,0.32,4.19,3.19,4.40
19,81770.0,37060.0,14140.0,-15840.0,29970.0,8150.0,0.63,2019-12-31,PETR4,-12990.0,...,0.145,0.047,0.404,0.133,0.270,0.480,0.35,3.13,2.13,2.22
20,77050.0,30010.0,14300.0,-16140.0,30440.0,9090.0,0.70,2019-09-30,PETR4,-7060.0,...,0.117,0.039,0.353,0.099,0.237,0.408,0.40,3.02,2.02,2.29
21,72570.0,30210.0,39240.0,-15790.0,54530.0,18870.0,1.45,2019-06-30,PETR4,-7890.0,...,0.112,0.037,0.350,0.089,0.235,0.385,0.42,3.18,2.18,2.37
22,80000.0,26420.0,14520.0,-15450.0,29970.0,4030.0,0.31,2019-03-31,PETR4,-6070.0,...,0.084,0.028,0.350,0.064,0.172,0.307,0.43,3.36,2.36,3.45
23,92720.0,31500.0,11580.0,-10930.0,22510.0,2100.0,0.16,2018-12-31,PETR4,-10030.0,...,0.098,0.031,0.356,0.074,0.185,0.310,0.42,3.10,2.10,2.52
24,98260.0,34640.0,17990.0,-10700.0,28690.0,6640.0,0.51,2018-09-30,PETR4,-13940.0,...,0.070,0.023,0.354,0.055,0.157,0.286,0.42,2.99,1.99,3.10
25,84400.0,31620.0,16980.0,-10960.0,27940.0,10070.0,0.77,2018-06-30,PETR4,-10100.0,...,0.046,0.015,0.341,0.038,0.139,0.280,0.38,3.01,2.01,3.35
26,74460.0,26770.0,18330.0,-11060.0,29380.0,6960.0,0.53,2018-03-31,PETR4,-9920.0,...,0.008,0.003,0.326,0.007,0.142,0.290,0.37,3.03,2.03,3.27
27,76510.0,25200.0,-930.0,-10450.0,9520.0,-5480.0,- 0.42,2017-12-31,PETR4,-13500.0,...,-0.002,-0.001,0.323,-0.002,0.133,0.283,0.35,3.15,2.15,3.58
28,71820.0,21240.0,8220.0,-10890.0,19100.0,266.0,0.02,2017-09-30,PETR4,-9430.0,...,0.029,0.009,0.321,0.027,0.177,0.333,0.35,3.07,2.07,3.08
29,67000.0,21370.0,15610.0,-10380.0,25990.0,316.0,0.02,2017-06-30,PETR4,-10660.0,...,-0.034,-0.011,0.330,-0.033,0.112,0.275,0.34,3.12,2.12,3.93
30,68370.0,23790.0,14880.0,-10770.0,25650.0,4450.0,0.34,2017-03-31,PETR4,-10020.0,...,-0.035,-0.011,0.330,-0.032,0.081,0.248,0.33,3.06,2.06,4.37
31,70490.0,22810.0,10540.0,-11230.0,21770.0,2510.0,0.19,2016-12-31,PETR4,-12580.0,...,-0.058,-0.016,0.318,-0.052,0.058,0.230,0.31,3.22,2.22,4.87
32,70440.0,23340.0,-10170.0,-12720.0,2540.0,-16460.0,- 1.26,2016-09-30,PETR4,-10190.0,...,-0.188,-0.058,0.316,-0.183,-0.122,0.042,0.32,3.09,2.09,26.05
33,71320.0,22820.0,7580.0,-11950.0,19530.0,370.0,0.03,2016-06-30,PETR4,-11850.0,...,-0.135,-0.048,0.306,-0.134,-0.064,0.083,0.36,3.02,2.02,13.00
34,70340.0,21010.0,8540.0,-12650.0,21190.0,-1250.0,- 0.10,2016-03-31,PETR4,-14670.0,...,-0.136,-0.050,0.306,-0.130,-0.056,0.078,0.38,3.27,2.27,14.96
35,85100.0,26850.0,-42230.0,-11570.0,-30670.0,-36940.0,- 2.83,2015-12-31,PETR4,-18210.0,...,-0.113,-0.044,0.306,-0.108,-0.041,0.079,0.41,3.53,2.53,15.56
36,82240.0,23760.0,6250.0,-9460.0,15710.0,-3760.0,- 0.29,2015-09-30,PETR4,-18040.0,...,-0.072,-0.030,0.292,-0.076,-0.014,0.097,0.39,3.22,2.22,13.03
37,79940.0,25560.0,9630.0,-9030.0,18660.0,531.0,0.04,2015-06-30,PETR4,-17560.0,...,-0.072,-0.033,0.276,-0.080,-0.048,0.054,0.41,2.80,1.80,18.89
38,74350.0,22410.0,13170.0,-8520.0,21690.0,5330.0,0.41,2015-03-31,PETR4,-17510.0,...,-0.061,-0.027,0.254,-0.066,-0.050,0.047,0.41,2.74,1.74,23.53
39,85040.0,22020.0,-33640.0,-8810.0,-24830.0,-26600.0,- 2.04,2014-12-31,PETR4,-21930.0,...,-0.062,-0.029,0.239,-0.064,-0.065,0.026,0.45,2.57,1.57,35.02
40,88380.0,20440.0,-4850.0,-7040.0,2190.0,-5340.0,- 0.41,2014-09-30,PETR4,-20150.0,...,0.033,0.015,0.229,0.034,0.056,0.144,0.44,2.39,1.39,5.88
41,82300.0,19020.0,8810.0,-7710.0,16520.0,4960.0,0.38,2014-06-30,PETR4,-19140.0,...,0.059,0.027,0.223,0.062,0.091,0.184,0.43,2.22,1.22,4.20
42,81540.0,19450.0,7760.0,-7120.0,14880.0,5390.0,0.41,2014-03-31,PETR4,-20690.0,...,0.063,0.031,0.229,0.068,0.102,0.195,0.45,2.26,1.26,3.91
43,81030.0,17020.0,6870.0,-7500.0,14370.0,6280.0,0.48,2013-12-31,PETR4,NaN,...,0.069,0.035,0.233,0.077,0.113,0.206,0.45,2.16,1.16,3.67
44,77700.0,16590.0,5990.0,-7600.0,13580.0,3390.0,0.26,2013-09-30,PETR4,NaN,...,0.073,0.039,0.238,0.084,0.112,0.203,0.46,2.22,1.22,3.51
45,73630.0,18710.0,11500.0,-6980.0,18480.0,6200.0,0.48,2013-06-30,PETR4,NaN,...,0.081,0.043,0.246,0.093,0.123,0.209,0.47,2.21,1.21,3.23
46,72540.0,18860.0,10010.0,-6380.0,16390.0,7690.0,0.59,2013-03-31,PETR4,NaN,...,0.058,0.032,0.242,0.068,0.103,0.184,0.47,2.07,1.07,3.20
47,73410.0,16560.0,5920.0,-5930.0,11850.0,7750.0,0.59,2012-12-31,PETR4,NaN,...,0.064,0.035,0.252,0.075,0.112,0.189,0.47,1.98,0.98,3.17
48,73790.0,18090.0,8790.0,-5780.0,14570.0,5570.0,0.43,2012-09-30,PETR4,NaN,...,0.056,0.032,0.262,0.068,0.121,0.201,0.47,1.89,0.89,2.85
49,68050.0,16020.0,4860.0,-5320.0,10170.0,-1350.0,- 0.10,2012-06-30,PETR4,NaN,...,0.060,0.035,0.280,0.073,0.137,0.214,0.47,1.86,0.86,2.71
50,66130.0,20240.0,11910.0,-4750.0,16660.0,9210.0,0.71,2012-03-31,PETR4,NaN,...,0.100,0.058,0.303,0.123,0.170,0.244,0.47,1.83,0.83,1.99
51,63730.0,16430.0,7350.0,-5740.0,13100.0,5050.0,0.39,2011-12-31,PETR4,NaN,...,0.109,0.064,0.316,0.136,0.181,0.254,0.47,1.82,0.82,1.93
52,64180.0,20360.0,11850.0,-4350.0,16200.0,6340.0,0.49,2011-09-30,PETR4,NaN,...,0.131,0.077,0.339,0.165,0.204,0.272,0.46,1.77,0.77,1.77
53,61470.0,20240.0,12210.0,-4090.0,16300.0,10940.0,0.84,2011-06-30,PETR4,NaN,...,0.232,0.108,0.350,0.182,0.209,0.278,0.59,1.72,0.72,1.49
54,54800.0,20200.0,12810.0,-3560.0,16370.0,10980.0,0.84,2011-03-31,PETR4,NaN,...,0.226,0.105,0.359,0.177,0.216,0.285,0.59,1.73,0.73,1.38